export const SET_FORGOT_PASSWORD_PENDING = 'SET_FORGOT_PASSWORD_PENDING';
export const SET_FORGOT_PASSWORD_SUCCESS = 'SET_FORGOT_PASSWORD_SUCCESS';
export const SET_FORGOT_PASSWORD_ERROR = 'SET_FORGOT_PASSWORD_ERROR';
export const SET_FORGOT_PASSWORD_EMAIL = 'SET_FORGOT_PASSWORD_EMAIL';