export const SET_LOGIN_PENDING = 'SET_LOGIN_PENDING';
export const SET_LOGIN_SUCCESS = 'SET_LOGIN_SUCCESS';
export const SET_LOGIN_ERROR = 'SET_LOGIN_ERROR';
export const SET_USER_TOKEN = "SET_USER_TOKEN";

export const SET_USER_TYPE = "SET_USER_TYPE";
export const SET_DOCTOR_FORM_STATUS= 'SET_DOCTOR_FORM_STATUS';
