export const SET_REQUEST_OTP_PENDING = 'SET_REQUEST_OTP_PENDING';
export const SET_REQUEST_OTP_SUCCESS = 'SET_REQUEST_OTP_SUCCESS';
export const SET_REQUEST_OTP_ERROR = 'SET_REQUEST_OTP_ERROR';

export const SET_VERIFY_OTP_PENDING = 'SET_VERIFY_OTP_PENDING';
export const SET_VERIFY_OTP_SUCCESS = 'SET_OTP_SUVERIFY_CCESS';
export const SET_VERIFY_OTP_ERROR = 'SET_OTP_VERIFY_ERROR';