export const SET_DOCTOR_REGISTRATION_PENDING = 'SET_DOCTOR_REGISTRATION_PENDING';
export const SET_DOCTOR_REGISTRATION_SUCCESS = 'SET_DOCTOR_REGISTRATION_SUCCESS';
export const SET_DOCTOR_REGISTRATION_ERROR = 'SET_DOCTOR_REGISTRATION_ERROR';