export const SET_PATIENT_PROFILE_PENDING = 'SET_PATIENT_PROFILE_PENDING';
export const SET_PATIENT_PROFILE_SUCCESS = 'SET_PATIENT_PROFILE_SUCCESS';
export const SET_PATIENT_PROFILE_ERROR = 'SET_PATIENT_PROFILE_ERROR';