export const SET_REQUEST_ACCOUNTS_PENDING = 'SET_REQUEST_ACCOUNTS_PENDING';
export const SET_REQUEST_ACCOUNTS_SUCCESS = 'SET_REQUEST_ACCOUNTS_SUCCESS';
export const SET_REQUEST_ACCOUNTS_ERROR = 'SET_REQUEST_ACCOUNTS_ERROR';


export const SET_REQUEST_USER_DETAILS_PENDING = 'SET_REQUEST_USER_DETAILS_PENDING';
export const SET_REQUEST_USER_DETAILS_SUCCESS = 'SET_REQUEST_USER_DETAILS_SUCCESS';
export const SET_REQUEST_USER_DETAILS_ERROR = 'SET_REQUEST_USER_DETAILS_ERROR';