
export const SET_DOCTOR_DETAILS_FORM_PENDING = 'DOCTOR_DETAILS_FORM_PENDING';

export const SET_DOCTOR_DETAILS_FORM_STEP_ZERO_FAILURE = 'DOCTOR_DETAILS_FORM_STEP_ZERO_FAILURE';
export const SET_DOCTOR_DETAILS_FORM_STEP_ZERO_SUCCESS = 'DOCTOR_DETAILS_FORM_STEP_ZERO_SUCCESS';
export const SET_DOCTOR_DETAILS_FORM_STEP_ZERO_DATA = 'DOCTOR_DETAILS_FORM_STEP_ZERO_DATA';

export const SET_DOCTOR_DETAILS_FORM_STEP_ONE_FAILURE = 'DOCTOR_DETAILS_FORM_STEP_ONE_FAILURE';
export const SET_DOCTOR_DETAILS_FORM_STEP_ONE_SUCCESS = 'DOCTOR_DETAILS_FORM_STEP_ONE_SUCCESS';
export const SET_DOCTOR_DETAILS_FORM_STEP_ONE_DATA = 'DOCTOR_DETAILS_FORM_STEP_ONE_DATA';

export const SET_DOCTOR_DETAILS_FORM_STEP_TWO_FAILURE = 'DOCTOR_DETAILS_FORM_STEP_TWO_FAILURE';
export const SET_DOCTOR_DETAILS_FORM_STEP_TWO_SUCCESS = 'DOCTOR_DETAILS_FORM_STEP_TWO_SUCCESS';
export const SET_DOCTOR_DETAILS_FORM_STEP_TWO_DATA = 'SET_DOCTOR_DETAILS_FORM_STEP_TWO_DATA';

export const SET_DOCTOR_DETAILS_FORM_STEP_THREE_FAILURE = 'DOCTOR_DETAILS_FORM_STEP_THREE_FAILURE';
export const SET_DOCTOR_DETAILS_FORM_STEP_THREE_SUCCESS = 'DOCTOR_DETAILS_FORM_STEP_THREE_SUCCESS';
export const SET_DOCTOR_DETAILS_FORM_STEP_THREE_DATA = 'DOCTOR_DETAILS_FORM_STEP_THREE_DATA';


export const SET_REQUEST_DOCTOR_DETAILS_FORM_STEP_FAILURE = 'SET_REQUEST_DOCTOR_DETAILS_FORM_STEP_FAILURE';
export const SET_REQUEST_DOCTOR_DETAILS_FORM_STEP_SUCCESS = 'SET_REQUEST_DOCTOR_DETAILS_FORM_STEP_SUCCESS';

export const SET_STEP_INDEX = "SET_STEP_INDEX";
export const SET_REDIRECT_TO_DASHBOARD = "SET_REDIRECT_TO_DASHBOARD";