
export const SET_MEDICAL_FORM_PENDING = 'MEDICAL_FORM_PENDING';

export const SET_MEDICAL_FORM_STEP_ZERO_FAILURE = 'MEDICAL_FORM_STEP_ZERO_FAILURE';
export const SET_MEDICAL_FORM_STEP_ZERO_SUCCESS = 'MEDICAL_FORM_STEP_ZERO_SUCCESS';
export const SET_MEDICAL_FORM_STEP_ZERO_DATA = 'MEDICAL_FORM_STEP_ZERO_DATA';

export const SET_MEDICAL_FORM_STEP_ONE_FAILURE = 'MEDICAL_FORM_STEP_ONE_FAILURE';
export const SET_MEDICAL_FORM_STEP_ONE_SUCCESS = 'MEDICAL_FORM_STEP_ONE_SUCCESS';
export const SET_MEDICAL_FORM_STEP_ONE_DATA = 'MEDICAL_FORM_STEP_ONE_DATA';

export const SET_MEDICAL_FORM_STEP_TWO_FAILURE = 'MEDICAL_FORM_STEP_TWO_FAILURE';
export const SET_MEDICAL_FORM_STEP_TWO_SUCCESS = 'MEDICAL_FORM_STEP_TWO_SUCCESS';
export const SET_MEDICAL_FORM_STEP_TWO_DATA = 'SET_MEDICAL_FORM_STEP_TWO_DATA';

export const SET_MEDICAL_FORM_STEP_THREE_FAILURE = 'MEDICAL_FORM_STEP_THREE_FAILURE';
export const SET_MEDICAL_FORM_STEP_THREE_SUCCESS = 'MEDICAL_FORM_STEP_THREE_SUCCESS';
export const SET_MEDICAL_FORM_STEP_THREE_DATA = 'MEDICAL_FORM_STEP_THREE_DATA';

export const SET_MEDICAL_FORM_STEP_FOUR_FAILURE = 'MEDICAL_FORM_STEP_FOUR_FAILURE';
export const SET_MEDICAL_FORM_STEP_FOUR_SUCCESS = 'MEDICAL_FORM_STEP_FOUR_SUCCESS';
export const SET_MEDICAL_FORM_STEP_FOUR_DATA = 'MEDICAL_FORM_STEP_FOUR_DATA';

export const SET_MEDICAL_FORM_STEP_FIVE_FAILURE = 'MEDICAL_FORM_STEP_FIVE_FAILURE';
export const SET_MEDICAL_FORM_STEP_FIVE_SUCCESS = 'MEDICAL_FORM_STEP_FIVE_SUCCESS';
export const SET_MEDICAL_FORM_STEP_FIVE_DATA = 'MEDICAL_FORM_STEP_FIVE_DATA';


export const SET_MEDICAL_FORM_STEP_SIX_FAILURE = 'MEDICAL_FORM_STEP_SIX_FAILURE';
export const SET_MEDICAL_FORM_STEP_SIX_SUCCESS = 'MEDICAL_FORM_STEP_SIX_SUCCESS';
export const SET_MEDICAL_FORM_STEP_SIX_DATA = 'MEDICAL_FORM_STEP_SIX_DATA';

// export const SET_MEDICAL_FORM_STEP_SEVEN_FAILURE = 'MEDICAL_FORM_STEP_SEVEN_FAILURE';
// export const SET_MEDICAL_FORM_STEP_SEVEN_SUCCESS = 'MEDICAL_FORM_STEP_SEVEN_SUCCESS';
// export const SET_MEDICAL_FORM_STEP_SEVEN_DATA = 'MEDICAL_FORM_STEP_SEVEN_DATA';

export const SET_REQUEST_MEDICAL_FORM_STEP_FAILURE = 'SET_REQUEST_MEDICAL_FORM_STEP_FAILURE';
export const SET_REQUEST_MEDICAL_FORM_STEP_SUCCESS = 'SET_REQUEST_MEDICAL_FORM_STEP_SUCCESS';

export const SET_STEP_INDEX = "SET_STEP_INDEX";
export const SET_REDIRECT_TO_DASHBOARD = "SET_REDIRECT_TO_DASHBOARD";