export const SET_RESET_PASSWORD_PENDING = "SET_RESET_PASSWORD_PENDING";
export const SET_RESET_PASSWORD_SUCCESS = "SET_RESET_PASSWORD_SUCCESS";
export const SET_RESET_PASSWORD_ERROR = "SET_RESET_PASSWORD_ERROR";