export default {
  locale: 'en',
  messages: {
    siteTitle: 'instaVC - Business Suite',
    addPost: 'Add Post',
    switchLanguage: 'Switch Language',
    twitterMessage: 'We are on Twitter',
    by: 'By',
    deletePost: 'Delete Post',
    createNewPost: 'Create new post',
    authorName: 'Author\'s Name',
    postTitle: 'Post Title',
    postContent: 'Post Content',
    submit: 'Submit',
    comment: `user {name} {value, plural,
          =0 {does not have any comments}
          =1 {has # comment}
          other {has # comments}
        }`,
    HTMLComment: `user <b style='font-weight: bold'>{name} </b> {value, plural,
          =0 {does not have <i style='font-style: italic'>any</i> comments}
          =1 {has <i style='font-style: italic'>#</i> comment}
          other {has <i style='font-style: italic'>#</i> comments}
        }`,
    nestedDateComment: `user {name} {value, plural,
          =0 {does not have any comments}
          =1 {has # comment}
          other {has # comments}
        } as of {date}`,
    loginTitle: 'Login',
    login_prompt: 'Please sign in to your instaVC account',
    email_address: 'Email Address',
    password :'Password',
    sign_in :'Sign in',
    sign_up :'Sign up',
    keep_signed_in :'Please keep me signed in',
    forgotten_password : 'I’ve forgotten my password',
    privacy_policy : 'Privacy Policy ',
    terms_conditions : 'Terms & Conditions',
    my_profile :'My Profile',
    work_education:'Work & Education',
    contacts:'Contact Info',
    personal_info :'Personal Info',
    company_details:'Company Details',
    about_me :'About Me',
    full_name   : 'Full Name',
    email   : 'E-mail',
    phone :'Phone Number',
    position:'Position',
    department : 'Department',
    activities  : 'Recent Activities',
    edit: 'Edit',
    cancel : 'Cancel',
    save : 'Save',
    delete : 'Delete',
    list : 'List',
    new : 'New',
    general_info : 'General Info',
    first_name : 'First Name',
    last_name :'Last Name',
    gender :'Gender',
    contact_details : 'Contact Details',
    male : 'Male',
    female: 'Female',
    corporate_directory : 'Corporate Directory',
    user_info : 'User Info',
    credential_access:'Credential & Access',
    default_room :'Default Room',
    business_id : 'Business Id',
    business_name : 'Business Name',
    business_type : 'Business Type',
    corporate_type : 'Corporate Type',
    website : 'Website',
    company_status:'Company Status',
    schedule_type : 'Schedule Type',
    name :'Name',
    address: 'Address',
    street :'Street',
    district :'District',
    state :'State',
    country :'Country',
    pincode :'Pincode',
    license_details :'License Details',
    publish_limit:'Publish Limit',
    room_limit:'Room Limit',
    no_p2p :'No. of P2P',
    subscriber_limit: 'Subscriber Limit',
    users_limit:'Users Limit',
    legal_doc_details : 'Legal Document Details',
    pan_number : 'PAN Number',
    tan_id : 'TAN Id',
    active : 'Active',
    inactive :'Inactive',
    calendar :'Calendar',
    contact_name : 'Contact Name',
    contact_phone_number:'Contact Phone Number',
    view :'View',
    title_company_details:'Below are the details about the Company you have created',
    title_category_details:'Below are the details about the Category you have created',
    corporate_info:"Corporate Info",
    all_corporates :"All Corporates",
    title_list_details:'Below are the list of',
    corporate_list : 'Corporate List',
    hidden : " ",
    company_code :'Company Code',
    role : "Role",
    new_user : 'New User',
    edit_user : 'Edit User',
    all_users : "All Users",
    date : 'Date',
    user_details : 'User Details',
    room : 'Room',
    smtp_details : 'SMTP Details',
    api_key : 'Api key',
    domain : 'Domain',
    username : 'Username',
    server : 'Server',
    smtp_setting : "SMTP Settings",
    basic_info : 'Basic Info',
    select_package : 'Select Package',
    room_name : 'Room Name',
    room_type : 'Conference Type',
    room_password : 'Room Password',
    other_details : 'Other Details',
    corporate_name : 'Corporate Name',
    host_password : 'Host Password',
    bridge_number : 'Bridge Number',
    room_manager : 'Room Manager',
    my_room : 'My Room',
    room_users : 'Room Users',
    room_user : 'Room User',
    new_room : 'New Room',
    all_rooms : 'All Rooms',
    add_user_to_room : 'Add User To Room',
    package_name : 'Package Name',
    title_created_room_details : 'Below are the details about the Room you have created.',
    room_license : 'Room License',
    mcu_server : 'Mcu Server',
    title_contact_details : 'Below are the users added to this Room',
    package_details : 'Package Details',
    package_manager : 'Package Manager',
    package_info : 'Package Info',
    package_price : 'Package Price',
    user_count : 'User Count',
    user_presence : 'User Presence',
    package_validity : 'Package Validity',
    server_location : 'Server Location',
    assigned_to : 'Assigned To',
    title_about_package : 'Below are the details about the package you have created.',
    search_contacts : 'Search Contacts',
    search_assigned_to_contacts : 'Search contacts to assign.',
    add : 'Add',
    dashboard  : 'Dashboard',
    my_account : 'My Account',
    manage_user : 'Manage Users',
    reports : 'Reports',
    ldap_settings : 'LDAP Settings',
    room_management : 'Room Management',
    package_management : 'Package Management',
    category_management: 'Category Management',
    logout : 'Log Out',
    settings : 'Settings',
    ldap_details :'LDAP Details',
    domain :'Domain',
    base_dn :'Base DN',
    url : 'URL',
    bind_cn :'Bind CN',
    bind_password :'Bind Password',
    force_login:'Force Login',
    new_category: 'New Category',
    all_categories: 'All Categories',
    edit_category: 'Edit Category',
    category_details: 'Category Details',
    category_name: 'Category Name',
    category_desc: 'Category Description',
    category_list:'Category List',
    package_list:'Package List',
    room_list:'Room List',
    user_list:'User List',
    corporate_detail:'Corporate Details',
    true: 'true',
    false :'false',
    conference :'Conference',
    lms :'LMS',
    crm :'CRM',
    presenter : 'Presenter',
    admin : 'Admin',
    user :'User',
    mix :'Mix',
    forward :'Forward',
    hybrid :'Hybrid',
    desc: 'Description',
    no_users_found : 'No Users Found.',
    my_contacts:'My Contacts',
    chat :'Chat',
    mute_unmute:'Mute / Unmute',
    disable_enable:'Disable / Enable',
    start_recoding:'Start Recording',
    expand_contract:'Expand / Contract',
    no_recent_contacts:'No Recent Contacts',
    add_your_contacts :'Add your contacts',
    close : 'Close',
    sandra_smith: 'Sandra Smith',
    say_something :'Say something...',
    video_quality:'Video Quality',
    languages : 'Languages',
    help : 'Help',
    add_contacts : 'Add Contacts',
    attach_file:'Attach file',
    search_contacts_add:'Search contacts to add to your contacts list.',
    set_language:'Set Language',
    set_video_qulity:'Set video resolution',
    push_the_message:'Push the message',
    invite_others:'Invite others to join instantly',
    regenerate : 'Regenerate',
    copy_this_link:'Copy this link',
    share_Link:'Share Link',
    open_mail_client:'Open Mail Client',
    start_conference:'Start Conference',
    create_new_room:'Create new Room',
    add_participants:'Add participants',
    search_room:'Search Room',
    my_rooms:'My Rooms',
    select_your_room:'Select your Room',
    presenter_mode:'Presenter Mode',
    conference_mode:'Conference Mode',
    valid_untill:'Valid Until',
    search_rooms:'Search Rooms...',
    schedules_new:'Schedule Conference',
    schedule_meeting:'Schedule Meeting',
    past_schedules:'Past Schedules',
    no_schedules:'No Schedules',
    create_schedule:'Create your schedule  by clicking the Schedule Conference button',
    meeting_name : 'Meeting Name',
    please_enter_meeting_name : 'Please enter meeting name',
    create_edit_conference :'Create/Edit Conference',
    choose_anavailable_date :'Choose an available date',
    set_start_time:'Set Start Time',
    // set_end_time:'Set End Time.',
    set_duration: 'Set Duration',
    recurring_schedule: 'Recurring Schedule',
    repeats : 'Repeats',
    repeat_every: 'Repeat Every',
    set_conference_password :'Set your conference password.',
    invite:'Invite',
    start : 'Start',
    organizer:'Organizer',
    edit_schedule:'Edit this schedule',
    delete_schedule :'Delete this schedule',
    invite_contacts : 'Invite contacts',
    invite_people:'Invite People',
    join_meeting:'Please join my meeting from your desktop, tablet or smartphone',
    conference_room_url:'Invitation URL',
    enter_email:'Enter email',
    please_enter:'Please enter the mail id...',
    enter_meeting_name:'Please enter the meeting name.',
    select_room:'Please select the Room.',
    minimum_date: 'Please select current or future date.',
    start_time_greater:'Start time should be greater than current time.',
    end_time_greater:'End time should be greater than start time.',
    video_resolution:'For SIF Video Resolution',
    video_graphics:'For Video Graphics Array (VGA) Video Resolution',
    hd_video:'For HD Video Resolution',
    full_hd:'For Full HD Video Resolution',
    online:'Online',
    away:'Away',
    offline:'Offline',
    do_not_disturb:'Do not disturb',
    locale : 'Locale',
    time_zone :'Time Zone',
    date_format :'Date Format',
    time_format : 'Time Format',
    currency_format: 'Currency Format',
    prefered_language:'Preferred Language',
    room_topic : 'Topics',
    my_topic : 'My Topic',
    room_topic_manager :'Room Topic Manager',
    topic_name : 'Topic Name',
    description : 'Description',
    topic_details : 'Topic Information',
    upload : 'Upload',
    upload_file : 'Upload File',
    upload_media : 'Upload Media',
    upload_sco : 'Upload SCO',
    topic_list : 'Topic List',
    upload_list : 'Upload List',
    file_name : 'File Name',
    openfile:'Download',
    questionnaire: 'Questionnaire',
    all_questionnaire: 'All Questionnaire',
    questionnaire_list: 'Questionnaire List',
    add_questionnaire: 'Add Questionnaire',
    questionnaire_details: 'Questionnaire Information',
    questionnaire_name: 'Questionnaire Name',
    questionnaire_type: 'Questionnaire Type',
    view_questionnaire: 'View Questionnaire',
    questions: 'Questions',
    questionnaire_details: 'Questionnaire Details',
    title_questionnaire_details: 'Below are the details about the questionnaire you have created.',
    selectroom :'Select Room',
    no_rooms:'No rooms have been created',
    create_a_room : 'Create a Room',
    requiedField : 'Please',
    help_content:'Help Content.',
    no_data_yet:'No Data Yet!',
    add_question: 'Add Question',
    upload_scorm: 'Upload SCORM',
    scorm: 'SCORM',
    scorm_filename: 'SCORM Filename',
    title_question_details : 'Below are the questions added to this questionnaire',
    deletefile : 'Delete present file',
    edit_questionnaire: 'Edit Questionnaire',
    local_settings:'Locale Settings',
    select_company : 'Select Company',
    select_gender : 'Select Gender',
    select_role : 'Select Role',
    files : 'Files',
    content : 'Content',
    edit_question: 'Edit Question',
    feedback: 'Feedback',
    all_feedback : "All Feedback",
    user_feedback : 'User Feedback',
    feedback_text:'Please enter your comment',
    assign_questionnaire: "Assign Questionnaire",
    title_questionnaire_assigned: 'Below are the questionnaires assigned to this topic',
    automatic : 'Automatic',
    set : 'Set',
    change_password : 'Change Password',
    old_pwd : 'Old Password',
    new_pwd : 'New Password',
    re_new_pwd : 'Retype new password',
    forgot_password : 'Forgot Password',
    reset_prompt : 'Reset Password',
    forgot_prompt : 'Kindly enter your email address',
    dd_mm_yyyy :'DD/MM/YYYY',
    dd_mm_yy:'DD/MM/YY',
    ddmmyyyy:'DD-MM-YYYY',
    hh_mm_ss:'HH:MM:SS',
    usd:'USD',
    indian_rupee:'Indian Rupee',
    english :'English',
    hindi :'Hindi',
    edit_corporate :'Edit Corporate',
    user_directory :'User Directory',
    new_corporate : "New Corporate",
    all_packages : 'All Packages',
    package_directory : 'Package Directory',
    new_package : 'New Package',
    edit_package : 'Edit Package',
    room_directory : 'Room Directory',
    room_details : 'Room Details',
    room_info :'Room Info',
    category_directory : 'Category Directory',
    category_info :'Category Info',
    smtp_info :'SMTP Info',
    ldap_info:'LDAP Info',
    upload_url : 'URL Upload',
    invalid_date : 'Please select / enter valid Date',
    invalid_start_time : 'Invalid start time',
    invalid_end_time : 'Invalid end time',
    invalid_enddate : 'Invalid end date',
    select_the_days : 'Please select the days',
    select_the_endson : 'Please select the ends on',
    enter_occurence : 'Please enter the no. of occurences',
    category_name : 'Category Name',
    all : 'All',
    image : 'Image',
    application : 'Application',
    video : 'Video',
    audio :'Audio',
    zip :'Zip',
    url: 'Link',
    document: 'Document',
    search:'Search....',
    result_list : 'Result List',
    candidate_name : 'Candidate Name',
    result_details : 'Result Details',
    my_groups : 'My Groups',
    no_recent_groups : 'No Recent Groups',
    add_your_groups : 'Add your groups',
    create_group : 'Create Group',
    group_name : 'Group Name',
    questionnaire_result : 'Result',
    room_feedback : 'Feedback List',
    user_name : 'User Name',
    over_all_rating : 'Over All Rating',   
    knowlegable_session: 'Knowledgeable Session',
    instructor_skills: 'Presenter Skills',
    content_sharing : 'Content Sharing',
    over_all_rating : 'Rating',
    user_comment : 'User Comment',
    audio_quality : 'Audio Quality',
    user_feedback_data : 'Feedback',
    individual_feedback : 'Feedback details submitted by user',
    feedback_details : 'Individual Feedback details',
    multiple_delete : 'Multiple Delete',
    no_recent_member : 'No Recent Members',
    add_your_members : 'Add your members',
    add_member : 'Add Member',
    search_members_add : 'Search contacts to add to your Gorup.',
    back_to_room : 'Back to Room',
    add_student : 'Add Attendee',
    instructor_name :'Presenter Name',
    room_student_to_instructor : 'Add Attendee to Presenter',
    search_students :'Search Attendee',
    whiteboard:'Whiteboard',
    screen_share : 'Screen Share',
    topics:'Topics',
    hand_raise :'Q&A',
    topics_list: 'Topics List',
    welcome_room:'Welcome to Room:',
    fulltopic:'Read more...',
    search_attendees:'Search Attendees',
    no_topics_yet:'No Topics Yet!..',
    list_topics:'Below are the list of topics related to this room.',
    have_schedule :'Already have a schedule',
    your_selected_date : 'Your selected dates',
    presenter:'Presenter',
    telepresence:'Telepresence',
    record:'Record',
    no_attendees_present:'No Attendees present',
    no_user_added:'No Users added to this room',
    delete_group : 'Delete group',
    location_name : 'Location Name',
    location_directory :'Location Directory',
    location_details : 'Location Details',
    location_list : 'Location List',
    title_created_location_details : 'Below are the details about the location you have created.',
    no_questions : 'No Questions',
    location_info : 'Location Info',
    edit_location : 'Edit Location',
    new_location:'New Location',
    all_locations:'All Locations',
    location : 'Location',
    room_location : 'Room Locations',
    course_location : 'Room Location',
    addlocation : 'Add Location',
    room_chat : 'Room Chat',
    title_location_details : 'Below are the locations added to this Room',
    viewprofile : 'View Profile', 
    back : 'Back',
    profile : 'Profile',
    add_feedback : 'Add Feedback',
    manage : 'Manage',
    ask : 'Ask',
    ask_question  : 'Ask Question',
    previous_questions : 'Previous Questions',
    post : 'Post',
    answers : 'Answers',
    make_speaker : 'Request Video',
    answer_the_question : 'Answer the Question',
    reply : 'reply',
    your_comment : 'Your Comment',
    post_comment : 'Comment',
    previous_answers : 'Previous Answers',
    comment_on_answer : 'Comment on Answer',
    make_this_user_the_speaker : 'Make this user the Speaker',
    delete_the_question : 'Delete the question',
    edit_the_question : 'Edit the question',
    see_all_answers : 'See all answers',
    media_resources:'Media Resources',
    documents:'Documents',
    questionnaires : 'Questionnaires',
    no_questionnaires_yet:'No Questionnaires Yet!',
    start_date:'Start Date',
    end_date:'End Date',
    choose_question_answers:'Choose the correct answer from the questions listed below',
    no_files_yet:'No Files Yet!',
    no_questions_yet:'No Questions Yet!',
    not_attempted:'Not Attempted!',
    locale_directory:'Locale Direcrory',
    share_your_screen :'Share your screen!',
    city_town : 'City / Town',
    landmark : 'Landmark',
    contact_information : 'Contact Information',
    website_and_social_links : 'Website and social links',
    basic_information : 'Basic Information',
    add_address : 'Add Address',
    add_website : 'Add Website',
    add_social_link : 'Add social link',
    add_basic_information : 'Add Basic Information',
    social_link : 'Social Link',
    birthday : 'Birthday',    
    save_changes : 'Save Changes',
    birth_year : 'Birth Year',
    add_a_social_links : 'Add a social link',
    add_college : 'Add College',
    add_workplace : 'Add Workplace',
    add_highSchool : 'Add High School',
    add_professionalSkills : 'Add Professional Skills',
    work_title : 'Work',
    professionalSkills_title : 'Professional Skills',
    college_title : 'College',
    highSchool_title : 'High School',
    work_education_timeperiod : 'Time Period',
    work_education_desciption : 'Description',
    work_education_graduated : 'Graduated',
    work_education_school : 'School',
    work_education_concentration : 'Concentration',
    work_education_company : 'Company',
    work_education_position : 'Position',
    work_education_university : 'University',
    work_education_workStatus : 'I currently work here',
    work_education_saveChanges : 'Save Changes',
    work_company_placeholder : 'Where have you worked?',
    work_position_placeholder : 'What is your job title?',
    college_university_placeholder : 'Which college/university did you attend?',
    school_placeholder : 'Which school did you attend?',
    sync : 'Sync',
    pointer: 'Pointer',
    pencil:'Pencil',
    square : 'Square',
    circle :'Circle',
    oval :'Oval',
    line :'Line',
    alphabets :'Alphabets',
    erase_all :'Erase All',
    fill_background_colors:'Fill Background Colors',
    background:'Background',
    stroke:'Stroke',
    line_color:'Line color',
    no_participants:'No Participants',
    no_conference_loaded:'No Conference Loaded...',
    loading:'Loading',
    loading_please_wait:'Loading! please wait',
    current_password : 'Current Password',
    new_password : 'New Password',
    retype_new_password : 'Retype New Password',
    please_provide_your_valuable_feedback : 'Please provide your valuable feedback',
    video_quality : 'Video Quality',
    rate_the_quality_of_the_video_you_experienced : 'Rate the quality of the video you experienced',
    audio_quality : 'Audio Quality',
    rate_the_quality_of_the_audio_you_experienced : 'Rate the quality of the audio you experienced',
    content_sharing : 'Content Sharing',
    rate_the_quality_of_the_content_sharing_you_experienced : 'Rate the quality of the content sharing you experienced',
    knowlegeable_session : 'Knowledgeable Session',
    rate_how_Knowlegeable_this_session_was : 'Rate how Knowledgeable this session was',
    instructor_skills : 'Presenter Skills',
    rate_how_good_instructor_presented_the_subject : 'Rate how good Presenter presented the subject',
    overall_rating : 'Overall Rating',
    provide_the_overall_rating : 'Provide the overall rating',
    your_comments : 'Your Comments',
    your_comments_are_highly_appreciated : 'Your comments are highly appreciated',
    no_thanks : 'No Thanks',
    poor : 'Poor',
    average : 'Average',
    good : 'Good',
    very_good : 'Very Good',
    excellent : 'Excellent',
    feedback_submit : 'Submit',
    become_host_to_access_bellow_features :'Become host to access bellow features',
    screen_shared:'Screen Shared!',
    you_are_sharing_your_screen:'You are sharing your screen!',
    ok : 'OK',
    warning:'Warning',
    delete_question_alert:'Are you sure you want to delete this question?',
    delete_category_alert:'Are you sure you want to delete this category?',
    delete_corporate_alert:'Are you sure you want to delete this corporate?',
    delete_location_alert:'Are you sure you want to delete this location?',
    delete_package_alert:'Are you sure you want to delete this package?',
    delete_address_alert:'Are you sure you want to delete this address?',
    delete_link_alert:'Are you sure you want to delete this website link?',
    delete_social_link_alert:'Are you sure you want to delete this social link?',
    delete_birth_day_alert:'Are you sure you want to delete birthday?',
    delete_gender_alert:'Are you sure you want to delete gender?',
    delete_school_alert: 'Are you sure you want to delete this school?',
    delete_college_alert: 'Are you sure you want to delete this college?',
    delete_workplace_alert: 'Are you sure you want to delete this workplace?',
    delete_professional_alert: 'Are you sure you want to delete this professional skill?',
    delete_user_alert : 'Are you sure you want to delete this user?',
    delete_room_alert : 'Are you sure you want to delete this room?',
    delete_topic_alert : 'Are you sure you want to delete this topic?',
    delete_file_alert : 'Are you sure you want to delete this file?',
    delete_all_files_alert : 'Are you sure you want to delete all this files?',
    delete_questionaire_alert : 'Are you sure you want to delete this questionnaire?',
    delete_schedule_alert : 'Are you sure you want to delete this schedule?',
    edit_schedule_alert : 'If you edit the schedule the invitation link needs  to be sent again. Do you really want to edit?',
    delete_whiteboardObjects_alert : 'Are you sure you want to delete?',
    logout_confirm_incall : 'You are in call, are you sure you want to logout?',
    author:'Author',
    selected_codec:'Selected Codec',
    start_time:'Start time',
    end_time:'End time',
    delete_room_user_alert:'Are you sure you want to remove the user?',
    chat_file_alert:'File Size should be less than 20MB!..',
    share_file_alert:'File Size should be less than 10MB!..',
    topic_file_alert:'File Size should be less than 20MB!..',
    topic_media_file_alert: 'File Size should be less than 100MB!..',
    url_alert:'Enter a URL!..',
    valid_url_alert :'Not a valid URL!..',
    unassign_question_alert:'Are you sure you want to unassign the questionnaire?',
    generate_meeting_alert:'Meetings already scheduled for this room, Do you want to regenarate?',
    questionnaire_alert:'Questionnaire not started yet!..',
    delete_group_alert:'Are you sure you want to delete this group?',
    delete_member_group_alert:'Are you sure you want to delete member from this group?',
    submitted_by : 'Submitted By',
    delete_room_user_alert:'Are you sure you want to remove the user?',
    feedback_submitted_successfully : 'Feedback submitted Successfully',
    submitted : 'Submitted',
    question:'Question',
    type :'Type',
    mark_correct_answer:'Enter the two answer choices and mark the correct answer',
    select_type:'Select Type',
    remove:'Remove',
    answer_choice:'answer choice',
    delete_this_location:'Delete this location',
    no_locations_yet:'No Locations Yet!!!',
    enter_the_answer_choices_and_mark_which_answer_is_correct:'Enter the answer choices, and mark which answer is correct',
    transport_title : 'Transport?',
    uploadtotopic_title : 'Choose the content type to upload files in this topic.',
    file_title : 'Files',
    media_title : 'Media',
    sco_title : 'Zip',
    youtube_url_title : 'YouTube URL:',
    upload_title : 'Upload',
    filetypes_title: 'File Types:',
    youtube_url_placeholder : 'Paste link here: Eg: https://www.youtube.com/channel/UCdPJhu2eYCXIDo5hcTDw0_g',
    answer_sheet:'Answer Sheet',
    answer_sheet_details:'The answer sheet details',
    grade:'Grade',
    open:'Open',
    close:'Close',
    select_location:'Select Location',
    remove_user_from_room:'Remove User from Room',
    add_user:'Add User',
    add_student:'Add Attendee',
    view_students:'View Attendees',
    list_results:'List Results',
    view_edit_questionaire_from_topic:'View/Edit Questionnaire from Topic',
    unassign_questionnaire_from_topic:'Unassign Questionnaire from Topic',
    remove_question_from_questionnaire:'Remove Question from Questionnaire',
    view_edit_question_from_questionnaire:'View/Edit Question from Questionnaire',
    participants_group:'Participants Group',
    participants_list : 'Participants List',
    enter_group_name : 'Enter group name',
    not_allowed : 'Not Allowed',
    no_questions_added_to_this_questionnaire:'No Questions added to this questionnaire.',
    feature_info : 'Features Info',
    features : 'Features',
    no_of_rooms : 'No. of Rooms',
    no_of_topics : 'No. of Topics',
    server_recording : 'Server Recording',
    client_recording : 'Client Recording',
    video_conference : 'Video Conference',
    continuous_presence : 'No. of Continuous Presence',
    title_groupParticipants_details : 'Below are participants added to this group',

    group_participants : 'Participants lists',
    delete_this_group:'Delete this group', 
    edit_group_name : 'Edit group name',
    add_participants_group : 'Add Participants to group',
    search_participants : 'Search Participants',
    delete_participant_alert : 'Do you want to remove this participant?',
    created_by : 'Created By', 
    please_enter_group_name : 'Group name can not be empty',
    please_enter_participant_name : 'Please select participant',
    participants_group_list : 'Participants group list',
    room_configuration : 'Room Configuration',
    room_feedback_title : 'Feedback',
    configure_feedback : 'Configure Feedback',
    feedbackType_title : 'Feedback Type',
    configration : 'Configuration',
    codecType_title : 'Codec Type',
    enableLive_title : 'Enable Live',
    assign_questionaire : 'Assign Questionnaire',
    delete_SMTPSettings_alert: 'Are you sure you want to delete this SMTP Settings?',     
    time_limit : 'Time Limit',
    no_time_limitations : 'No Time Limitations',
    delete_LDAPSettings_alert :'Are you sure you want to delete this LDAP Settings?',
    previous:'Previous',
    next: 'Next',
    back_to_uploadlist :'Back to UploadList',
    enable_swot : 'Enable SWOT',
    select_an_answer_otherwise_it_will_not_be_considered_for_evaluation : 'Select an answer, otherwise it will not be considered for evaluation',
    export_users : 'Export Users',
    import_users : 'Import Users',
    import_format : 'Import Format',
    createdby:'CreatedBy',
    count:'Count',
    please_enter_the_question:'Please enter the Question',
    invalid_mail_id:'Invalid mail id.',
    accept : 'Accept',
    reject : 'Reject',
    request_pending:'Request Pending',
    start_chating:'Start chatting....!',
    pdf_view : 'PDF View',
    uploading_please_wait : 'Uploading! please wait',
    host_access : 'Host Access',
    become_host : 'Become Host',
    become_a_host: 'Become a Host',
    request_access_share: 'Request access to share screen / document',
    revoke : 'Revoke',
    enter_host_password : 'Enter Host Password',
    host_error : 'In-correct Host Password, please try again.',
    revoke_error : 'You are already Host. Do you want to Revoke...?',
    set_desc : 'Set Description',
    remove_participants_from_group : 'Remove participant from group',
    confirm_password : 'Confirm password',
    no_data_found : 'No data found',
    invalid_group_name : 'Invalid group name',
    no_groups_found : 'No Groups Found',
    start_class : 'Start Class',
    join_class : 'Join Class',
    create_a_class : 'Create a class',
    upcoming_classes : 'Upcoming Schedules',
    past_classes : 'Past Schedules',
    have_class : 'Already have a schedule',
    create_edit_class :'Create/Edit Class',
    class_name : 'Class Name',
    please_enter_class_name : 'Please enter meeting name',
    my_classes : 'My classes',
    set_class_password :'Set your class password.',
    edit_class:'Edit this class',
    delete_class :'Delete this class',
    select_language :'Select Language',
    no_data_found : 'No data found',
    edit_class_alert : 'If you edit the class the invitation link needs  to be sent again. Do you really want to edit?',
    delete_class_alert : 'Are you sure you want to delete this class?',
    submitted_on : 'Submitted On',
    delete_Profile_image_alert : 'Are you sure you want to delete your Profile Picture',
    room_options : "Room options",
    room_assignments : 'Assignments',
    assignment_list : 'Assignment List',
    assignment_details : 'Assignment Information',
    assignment_name : 'Assignment Name',
    room_assignment_manager :'Room Assignment Manager',
    list_assignments: 'Below are the list of assignments related to this room.',
    no_assignments_yet:'No Assignments Yet!..',
    submissions: 'Submissions',
    submission_list: 'Submission List',
    student_name: 'Student Name',
    back_to_assignments: 'Back To Assignments',
    file : 'File',
    select : 'Select',
    add_topics : 'Add topics to room',
    become_host_to_share_your_document :'Become host to share your document',
    share_your_document :'Share your document!',
    share_your_screen_document: 'Share your screen / document!',
    manage_assignments : 'Manage Assignments',
    manage_questionnaire : 'Manage Questionnaire',
    plagiarism: 'Plagiarism',
    drag: 'Drag',
    delete_assignment_alert : 'All submissions will also be deleted, Are you sure you want to delete this assignment?',
    refresh_schedules :'Refresh Schedules',
    schedules : 'Schedules',
    refresh_rooms :'Refresh Rooms',
    creating_please_wait : 'Creating! please wait',
    updating_please_wait : 'Updating! please wait',
    enable : 'Enable',
    publish: 'Publish',
    categories : 'categories.',
    corporates : 'corporates.',
    feedbacks : 'feedbacks.',
    locations : 'locations.',
    packages : 'packages.',
    participants : 'participants in the group.',
    rooms : 'rooms.',
    users : 'users.',
    list_topic : 'topics.',
    list_files : 'files.',
    list_certificates : 'certificates',    
    results : 'results.',
    polls : 'Polls',
    poll_list : 'Poll List',
    list_polls: 'Below are the list of polls related to this room.',
    no_polls_yet: 'No Polls Yet!..',
    package_validFrom : 'Valid From',
    create_poll : 'Create Poll',
    option : 'Option',
    package_validFrom : 'Valid From',
    title_created_plagiarism_details :'Below are the details about the plagiarism check for upload.',
    plagiarism_info : 'Plagiarism Info',
    percents :'Percents',
    copied_words : 'No.of CopiedWords',
    comparison_report  : 'Comparison Report',
    cached_version : 'Cached Version',
    title : 'Title',
    introduction : 'Introduction',
    embeded_comparison : 'Embeded Comparison',
    plagiarism : 'Plagiarism',
    publish : 'Publish',
    published : 'Published',
    update_poll : 'Update Poll',
    delete_poll_alert : 'Are you sure you want to delete this poll?',
    delete_poll : 'Delete Poll',
    broadcast : 'Broadcast News',
    broadcast_news_list : 'Broadcast News list ',
    no_broadcast : 'No broadcast News',
    broadcast_list : 'Broadcast list',
    no_submittions_yet: 'No Submissions Yet!..',
    list_poll_submissions : 'Below are the list of submissions related to this poll.',
    poll_analysis : 'Below is the analysis chart related to this poll.',
    delete_broadcast_alert:'Are you sure you want to delete this broadcast news?',
    view_comments : 'Comments',
    view_all_comments : 'View all comments',
    edit_comment : 'Edit Comment',
    delete_comment : 'Delete comment',
    reply_on_comment : 'Reply on comment',
    reply_comment : 'Reply',
    previous_comments : 'Previous comment',
    comment_on_broadcast_news : 'Comment on broadcast news',
    your_reply : "Reply on comment",
    delete_broadcast_alert:'Are you sure you want to delete this broadcast?',
    refresh_polls :'Refresh Polls',
    studentId : 'Student Id',
    view_result : 'View Result',
    submit_poll : 'Submit Poll',
    attendance : 'Attendance',
    please_enter_the_broadcast : 'Please enter broadcast news',
    total_attendance: 'Total Attendance',
    student_list: 'Student List',
    class_list: 'Class List',
    expiry_Date : 'Expiry Date',
    students: 'students',
    overall: 'OverAll',
    detailed: 'Detailed',
    classes: 'classes',
    view_attendance:'View Attendance',
    assignment_reports:'Assignment Reports',
    assignment_list: 'Assignment List',
    my_reports: 'My Reports',
    created_date: 'Created Date',
    expiry_date : 'Expiry Date',
    assignment: 'Assignment',
    test_reports: 'Test Report',
    active_users: 'Active Users',
    current_day : 'Current Day',
    recurring : 'Recurring',
    current_recurring : 'Delete Current Day / Recurring',
    delete_current_recurring : 'Do you want to delete current day (or) recurring schedule?',
    title_user_details:'Below are the details about the user you have created',
    registration_prompt:'Please fill below fields for registration',
    institute_name: 'Please enter institute name',
    please_enter_institute_name : 'Please enter institute name',
    inactive_user : 'Registered User',
    activate_user : 'Activate User',
    active_user : 'Active User',
    inactive_user_list : 'In active user list',
    Marks : 'Marks',
    total_marks : 'Total Marks',
    multiple_choice_answers : 'Multiple choice answers',
    multiple_responsive_answers : 'Multiple responsive answers',
    true_false : 'Trues or False answers',
    active_users_list :'Active Users List',
    course_attendance : 'Course Attendance',
    show_result : 'Show Result',
    student_reg_form : 'Student registration form',
    already_registered_user : 'Already registered?',
    i_agree : 'I Agree',
    terms_conditions : 'Terms and Conditions',
    grade_configuration : 'Grade Configuration',
    title_grade_configuration : 'Configure questionnaire grades here.',
    title_view_grade_configuration : 'Below are the grades which will be reflected in questionnaire result.',
    fullcalender : 'Full Calendar',
    select_duration : 'Please Select the Duration',
    set_hours : 'Set Hours',
    set_minutes : 'Set Minutes',
    checkin_time : 'Check-In Time',
    checkout_time : 'Check-Out Time',
    topic_report : 'Topics Reports ',
    course_view : 'Course View',
    topic_name : 'Topic Name',
    viewed_topics : 'Viewed Topics',
    topic_viewed_users : 'Topic Viewed Users',
    description : 'Description',
    status : 'Status',
    deleted_user : 'Deleted user',
    registered : 'Registered',
    deleted : 'Deleted',
    deleted_list : 'Deleted users',
    active_user_list : 'Active users',
    registered_user_list : 'Registered users',
    skip : 'Skip',
    all_participants_groups: 'All participants groups',
    from : 'From',
    to : 'To',
    no_replies : 'No Replies',
    no_answers :'No Answers',
    link_is_either_expired_or_broken:'Link is either expired or broken',
    summary : 'Summary',
    room_students : 'Room Students',
    topic_content : 'Topic Content',
    you_are_in_mange_users_panel:'You are in manage users panel',
    work_edu_details:'View Work and Education',
    view_contact_details:'View Contact',
    view_locale:'View Locale',
    you_are_in_active_users_panel : 'You are in active users panel',
    you_are_in_my_profile_panel : 'You are in my profile panel',
    you_are_in_package_list_panel : 'You are in package management panel',
    you_are_in_corporate_list_panel : 'You are in corporate panel',
    you_are_in_category_list_panel : 'You are in category management panel',
    you_are_in_room_list_panel :'You are in room management panel',
    you_are_in_location_list_panel : 'You are in location panel',
    you_are_in_participant_group_list_panel :'You are in participant group panel',
    you_are_in_questionarie_list_panel : 'You are in questionarie panel',
    edit_grade_configuaration : 'Edit grade configuaration',
    You_are_in_reports_list_panel : 'You are in reports panel',
    add_assignment : 'Add Assignment',                                                   
    users_activity : 'Users Activity',
    Update : "Update",
    blocked: 'Blocked',
    guest: 'Guest',
    requiedFieldText : 'Please enter',
    requiedFieldDate : 'Please select',
    validInputData : 'Please enter valid',
    select_dropdown : 'select',
    save_publish:'Save & Publish',
    connect_with_social_link:'Connect with Social Links',
    request_for_share_document : 'Request for share screen / document',
    requested_for_share_document_please_wait : 'Requested for share screen / document, Please wait .....',
    confirm_unassign_questionnaire_topics : 'Are you sure you want to unassign questionnaire as there are results based on this questionnaire?',
    update_publish : 'Update & Publish',
    invalid_file_format : 'Invalid file format.',
    confirm_delete_question_from_questionnaire : 'Are you sure you want to delete question from questionnaire as there are results based on question?',
    stop_screen_share: 'Stop Screen Share',
    pause_screen_share: 'Pause Screen Share',
    play_screen_share: 'Play Screen Share',
    add_students : 'Add student',
    confirm_submit_alert : 'Are you sure you want to submit?',
    user_reg_form : 'User registration form',
    registration_please_wait : 'Registering, Please wait',
    student_data_not_found : 'Student data not found',
    individual_user : 'Individual User',
    group : 'Group',
    add_groups : 'Add Groups',
    edit_room : 'Edit Room',
    edit_profie : 'Edit Profile',
    create_topic:'Create Topic',
    new_questionnaire: 'New Questionnaire',
    student_assignment_list_title : 'assignments which you have submitted',
    evaluation_not_yet_done : 'Evaluation not yet done',
    instructor_feedback : "Instructor's Feedback",
    total_assignment_marks : 'Total Assignment Marks',
    scored_marks : 'Scored Marks',
    add_another_field : 'Add another field',
    maximum_marks : 'Maximum Marks',
    total_score : 'Total Score', 
    load_more:'load more..',
    note : 'Note',
    default:'Default',
    proxy:'Proxy',
    quality : 'Quality',
    best_quality:'Best Quality',
    better_quality:'Better Quality',
    standard:'Standard',
    better_speed:'Better Speed',
    best_speed:'Best Speed',
    ends_on:'Ends',
    after :'After',
    occurences:'occurences',
    repeat_on:'Repeat On',
    On : 'On',
    No_Questionnaires_assigned_to_this_topic : 'No Questionnaires assigned to this topic.',
    total_percentage : 'Total Percentage',
    options : 'Options',
    revoke_host:'Revoke Host',
    become_host:'Become Host',
    video_settings:'Video Settings',
    mute_unmute:'Mute/Unmute',
    remote_mute_unmute : 'Remote Mute/Unmute',
    full_Screen:'Full Screen',
    share : 'Share',
    volume_on_off:'Volume On/Off',
    become_speaker:'Become Speaker',
    revoke_speaker : 'Revoke Speaker',
    become_presenter : 'Become Presenter',
    revoke_presenter:'Revoke Presenter',
    add_another_field: 'Add Another Field',
    today : 'Today',
    yesterday: 'Yesterday',
    last_seven_days: 'Last 7 days',
    last_thirty_days: 'Last 30 days',
    custom: 'Custom',
    date_range: 'Date Range',
    apply : 'Apply',
    not_loggedin_users : 'Not Logged-In Users',
    loggedin_users: 'Logged-In Users',
    loggedin_users_status: 'Logged-In Users Status',
    present_instructors: 'Present Instructors',
    absent_instructors: 'Absent Instructors',
    present_students:'Present Students',
    absent_students:'Absent Students ',
    instructors_attendance: 'Instructors Attendance',
    students_attendance: 'Students Attendance',
    percentage : 'Percentage',
    offline_visits: 'Offline Visits',
    online_visits: 'Online Visits',
    absent_schedules: 'Absent Schedules',
    total_schedules: 'Total Schedules',
    total_attendance: 'Total Attendance',
    count: 'Count',
    back_to_list: 'Back to List',
    back_to_reports: 'Back to Reports',
    completely_viewed_topic_users: 'Completely Viewed Topic Users',
    partially_viewed_topic_users: 'Partially Viewed Topic Users',
    not_AtAll_Viewed_Topic_Users: 'Not At All Viewed Topic Users',
    viewed_users : 'Viewed Users',
    completely_viewed_topics: 'Completely Viewed Topics',
    partially_viewed_topics: 'Partially Viewed Topics',
    notAtAll_Viewed_Topics: 'Not At All Viewed Topics',
    user_viewed_topics:'User Viewed Topics',
    topics_viewed: 'Topics Viewed',
    topic_users: 'Users',
    clear_room_chat: 'Clear Chat',
    delete_room_chat_alert: 'Are you sure you want to clear the chat?',
    join: 'Join',
    access_denied : 'Access Denied',
    video_bit_rate: 'Video Bit Rate',
    audio_bit_rate: 'Audio Bit Rate',
    evaluate_assignment:'Evaluate Assignment',
    back_to_submissions: 'Back To Submissions',
    Persian: 'Persian',
    submit : 'Submit',
    make_speaker_vedio : 'Make Speaker',
    Connection_Request : 'Connection Request',
    message:'Message',
    sources:'Sources',
    resolutions:'Resolutions',
    camera :'Camera',
    Audio_Inputs :'Audio Inputs',
    Please_enter_Company: 'Please enter Company',
    Please_enter_Position: 'Please enter Position',
    Please_enter_valid_City_Town: "'Please enter valid City/ Town' (Special charecters are not allowed)",
    Please_enter_valid_Country: 'Please enter valid Country',
    Please_enter_valid_From_Date: 'Please enter valid From Date',
    From_date_cannot_be_in_future: 'From date cannot be in future',
    Please_enter_valid_To_Date: "Please enter valid To Date",
    From_date_and_To_date_cannot_be_same: 'From date and To date cannot be same',
    To_date_should_be_greater_than_From_date: 'To date should be greater than From date',
    Please_enter_School: 'Please enter School',
    School_field_cannot_have_empty_spaces: "School field can't have empty spaces",
    Please_enter_University: 'Please enter University',
    University_field_cannot_have_empty_spaces: "University field can't have empty spaces",
    Please_enter_atleast_one_skill: "Please enter atleast one skill",
    Please_enter_Address: 'Please enter Address',
    Please_enter_a_valid_Address: 'Please enter a valid Address',
    Please_enter_City: 'Please enter City',
    Please_enter_a_valid_City: 'Please enter a valid City',
    Please_enter_Zip: "Please enter Zip",
    Please_enter_a_valid_Zip: 'Please enter a valid Zip',
    Please_enter_website: 'Please enter website',
    Please_enter_valid_website: 'Please enter valid website',
    Please_enter_social_link: 'Please enter social link',
    Please_enter_valid_social_link: 'Please enter valid social link',
    Please_enter_valid_Date_of_birth: 'Please enter valid Date of birth',
    Date_of_birth_cannot_be_future_Date: "Date of birth can't be future Date",
    Please_select_Gender: ' Please select Gender',
    Please_enter_Current_Password: 'Please enter Current Password',
    Please_enter_New_Password: 'Please enter New Password',
    Please_enter_Confirm_password: 'Please enter Confirm password',
    New_Password_and_Confirm_password_should_be_same: 'New Password and Confirm password should be same.',
    Assignment_name_cannot_have_only_white_spaces: "Assignment name can't have only white spaces",
    Please_enter_Assignment_Name: 'Please enter Assignment Name',
    Please_enter_Question: 'Please enter Question',
    please_select_type: ' please select type',
    Please_enter_Options: ' Please enter Options',
    Provide_atleast_Two_Options: 'Provide atleast Two Options',
    Options_cannot_be_same: "Options can't be same",
    Please_select_an_Answer: 'Please select an Answer',
    Marks_cannot_be_empty: "Marks can't be empty",
    Marks_can_only_have_Numbers: ' Marks can only have Numbers',
    Please_enter_a_valid_Name: ' Please enter a valid Name',
    Please_enter_valid_Email_id: 'Please enter valid Email id',
    Please_enter_Password: ' Please enter Password',
    Passwords_are_not_matching: 'Passwords are not matching',
    Please_enter_valid_City_Name: 'Please enter valid City Name',
    Please_enter_valid_State_Name: ' Please enter valid State Name',
    Please_accept_Term_conditions: 'Please accept Terms & conditions',
    Please_enter_institute_name: 'Please enter institute name',
    Enter_at_least_three_letters_to_search: 'Enter at least three letters to search',
    support_center: 'Support Center',
    open_a_new_ticket: 'Open a New Ticket',
    check_ticket_status: 'Check Ticket Status',
    troubleshoot: 'Troubleshoot',
    edit_current_day_recurring: 'Edit Current Day / Recurring',
    want_to_edit_current_day_or_recurring_schedule: 'Do you want to Edit Current day (or) recurring schedule?',
    want_to_delete_current_day_or_recurring_schedule: 'Do you want to delete Current day (or) recurring schedule?',
    delete_current_day_recurring: 'Delete Current Day / Recurring',
    duration_time_should_be_greaterthan_current_time: 'duration time should be greaterthan current time',
    Please_select_the_duration: 'Please select the duration',
    Please_fill_all_the_fields: 'Please fill all the fields',
    question_name_cannot_have_only_white_spaces: "Question name can't have only white spaces",
    options_cannot_have_only_white_spaces: "Options can't have only white spaces",
    upload_new: 'Upload New',
    profile_picture: 'Profile Picture',
    current: 'Current',
    recurring: 'Recurring',
    profile_picture:'Profile Picture',
    Please_select_any_option :'Please select any option',
    go_back:'Go back',
    phne:'Phone',
    Current:'Current',
    Personal_Information : 'Personal Information',
    Work_Places : 'Work Places',
    dob:'DOB',
    Social_Links:'Social Links',
    Connections : 'Connections',
    All_Connections:'All Connections',
    View_all: 'View all',
    Hide_all:'Hide all',
    hide: 'Hide',
    enter_schedule_password: 'Enter schedule password',
    conference_access: 'Conference access',
    please_enter_schedule_password: 'Please enter schedule password',
    invalid_or_expire_room: 'It looks an invalid room or your room is expired',
    unautharized_request: 'It looks an unautharized request',
    invalid_user: 'It looks you are an invalid user',
    invalid_room: 'It looks an invalid room',
    invalid_or_expire_package: 'It looks an invalid package or your package is expired',
    export_chat: 'Export Chat',
    download_certificate: 'Download Certificate',
    topics_completed: 'Topics Completed',
    certificates: 'Certificates',    
    certificate_approved: 'Certificate Approved',
    select_questionnaire : "Select Questionnaire",
    questionnaire_name_error : "Please enter Questionnaire Name",
    questionnaire_description_error : "Please enter Description",
    clone_from_previoues_questionnaire: "Clone from previous Questionnaire",
    select_questionnaire: "Please select questionnaire",
    topic_completed: 'If topic completes',
    i_have_completed_this_topic: 'I have completed the topic', 
    continous_user_presence_exceeded : 'User limit exceeded, Please contact admin',
    update_basic_information : 'Update Basic Information',
    adding_question_please_wait : 'Adding question, please wait...',
    index: "Index",
    add_index_topics : 'Add Index to topics',
    topic_index_alert : 'Do you want to change this topic index',
    no_topic_published:'Topics not yet published',
    topic_index: 'Index',
    scorm_content: 'Scorm Content',
    mcu_server_down: 'MCU Server Down'
  },
};
