export default {
  locale: 'hi',
  messages: {
    siteTitle: 'instaVC - Business Suite',
    addPost: 'Add Post',
    switchLanguage: 'Switch Language',
    twitterMessage: 'We are on Twitter',
    by: 'By',
    deletePost: 'Delete Post',
    createNewPost: 'Create new post',
    authorName: 'Author\'s Name',
    postTitle: 'Post Title',
    postContent: 'Post Content',
    submit: 'Submit',
    comment: `user {name} {value, plural,
        =0 {does not have any comments}
        =1 {has # comment}
        other {has # comments}
      }`,
    HTMLComment: `user <b style='font-weight: bold'>{name} </b> {value, plural,
        =0 {does not have <i style='font-style: italic'>any</i> comments}
        =1 {has <i style='font-style: italic'>#</i> comment}
        other {has <i style='font-style: italic'>#</i> comments}
      }`,
    nestedDateComment: `user {name} {value, plural,
        =0 {does not have any comments}
        =1 {has # comment}
        other {has # comments}
      } as of {date}`,
    loginTitle: 'लॉग इन करें',
    login_prompt: 'कृपया अपने instaVC खाते में साइन इन करें',
    email_address: 'ईमेल पता',
    password :'पासवर्ड',
    sign_in :'साइन इन करें',
    sign_up :'साइन अप करें',
    keep_signed_in :'कृपया मुझे साइन इन रखें',
    forgotten_password : 'मैं अपना पासवर्ड भूल चूका हूँ',
    privacy_policy : 'गोपनीयता नीति',
    terms_conditions : 'नियम एवं शर्तें',
    my_profile :'मेरी प्रोफाइल',
    work_education:'काम और शिक्षा',
    contacts:'संपर्क जानकारी',
    personal_info :'व्यक्तिगत जानकारी',
    company_details:'संस्थान के विवरण',
    about_me :'मेरे बारे में',
    full_name   : 'पूरा नाम',
    email   : 'ईमेल',
    phone :'फ़ोन नंबर',
    position:'पद',
    department : 'विभाग',
    activities  : 'क्रियाएँ',
    edit: 'संपादित करें',
    cancel : 'रद्द करे',
    save : 'जमा करे',
    delete : 'मिटाना',
    list : 'सूची',
    new : 'नया',
    general_info : 'सामान्य जानकारी',
    first_name : 'पहला नाम',
    last_name :'अंतिम नाम',
    gender :'लिंग',
    contact_details : 'संपर्क विवरण',
    male : 'पुस्र्ष',
    female: 'महिला',
    user_info : 'उपयोगकर्ता जानकारी',
    credential_access:'क्रेडेंशियल और प्रवेश',
    default_room :'डिफ़ॉल्ट पाठ्यक्रम',
    business_id : 'व्यवसाय आईडी',
    business_name : 'व्यवास्यक नाम',
    business_type : 'व्यापार के प्रकार',
    corporate_type : 'कंपनी के प्रकार',
    website : 'वेबसाइट',
    company_status:'कंपनी की स्थिति',
    schedule_type : 'शेड्यूल के प्रकार',
    name :'नाम',
    address: 'पता',
    street :'सड़क',
    district :'जिला',
    state :'राज्य',
    country :'देश',
    pincode :'पिन कोड',
    license_details :'लाइसेंस विवरण',
    publish_limit:'प्रकाशित सीमा',
    room_limit:'पाठ्यक्रम सीमा',
    no_p2p :'पी 2 पी की संख्या',
    subscriber_limit: 'सब्सक्राइबर सीमा',
    users_limit:'उपयोगकर्ताओं को सीमित',
    legal_doc_details : 'कानूनी दस्तावेज विवरण',
    pan_number : 'पैन नंबर',
    tan_id : 'टैन पहचान पत्र',
    active : 'सक्रिय',
    inactive :'निष्क्रिय',
    calendar :'कैलेंडर',
    contact_name : 'संपर्क नाम',
    contact_phone_number:'संपर्क दूरभाष क्रमांक',
    view :'दृश्य दृष्टि',
    title_company_details:'नीचे आपके द्वारा बनाई गई कंपनी के बारे में विवरण दिया गया है',
    title_category_details:'नीचे आपके द्वारा बनाई गई श्रेणी के बारे में विवरण दिया गया है',
    corporate_info:"कॉर्पोरेट जानकारी",
    all_corporates :"सभी निगमों",
    title_list_details:'नीचे दी गई सूची',
    corporate_list : 'कॉर्पोरेट सूची',
    hidden : " ",
    company_code :'कंपनी कोड',
    role : "भूमिका",
    new_user : 'नया उपभोक्ता',
    edit_user : 'यूजर को संपादित करो',
    all_users : "सभी उपयोगकर्ताओं",
    date : 'तारीख',
    user_details : 'उपयोगकर्ता विवरण',
    room : 'पाठ्यक्रम',
    smtp_details : 'एसएमटीपी विवरण',
    api_key : 'एपीआई कुंजी',
    username : 'उपयोगकर्ता नाम',
    server : 'सर्वर',
    basic_info : 'बुनियादी जानकारी',
    select_package : 'पैकेज को चुन ले',
    room_name : 'पाठ्यक्रम का नाम',
    room_type : 'सम्मेलन प्रकार',
    room_password : 'पाठ्यक्रम का पासवर्ड',
    other_details : 'अन्य जानकारी',
    corporate_name : 'कंपनी का नाम',
    host_password : 'होस्ट पासवर्ड',
    bridge_number : 'ब्रिज नंबर',
    room_manager : 'पाठ्यक्रम प्रबंधक',
    my_room : 'मेरा पाठ्यक्रम',
    room_users : 'पाठ्यक्रम उपयोगकर्ता',
    room_user : 'पाठ्यक्रम उपयोगकर्ता',
    new_room : 'नया पाठ्यक्रम',
    all_rooms : 'सभी पाठ्यक्रम',
    add_user_to_room : 'पाठ्यक्रम में उपयोगकर्ता जोड़ें',
    package_name : 'पैकेज का नाम',
    title_created_room_details : 'नीचे आपके द्वारा बनाए गए पाठ्यक्रम के बारे में विवरण दिया गया है',
    room_license : 'पाठ्यक्रम लाइसेंस',
    mcu_server : 'एमसीयू सर्वर',
    title_contact_details : 'इस पाठ्यक्रम में जोड़े गए संपर्क नीचे दिए गए हैं',
    package_details : 'पैकेज के ब्यौरे',
    package_manager : 'पैकेज प्रबंधक',
    package_info : 'पैकेज जानकारी',
    package_price : 'पैकेज कीमत',
    user_count : 'उपयोगकर्ता की संख्या',
    user_presence : 'उपयोगकर्ता उपस्थिति',
    package_validity : 'पैकेज वैधता',
    server_location : 'सर्वर स्थान',
    assigned_to : 'को सौंपना',
    title_about_package : 'नीचे आपके द्वारा बनाए गए पैकेज के बारे में विवरण दिया गया है',
    search_contacts : 'खोजें संपर्क',
    search_assigned_to_contacts : 'असाइन करने के लिए संपर्क खोजें',
    // add : 'जोड़ना',
    add : 'जोड़े',
    settings : 'सेटिंग्स',
    dashboard  : 'डैशबोर्ड',
    my_account : 'मेरा खाता',
    corporate_directory : 'कॉर्पोरेट निर्देशिका',
    smtp_setting : "एसएमटीपी सेटिंग",
    manage_user : 'उपयोगकर्ताओं को प्रबंधित करें',
    reports : 'रिपोर्ट',
    ldap_settings :'LDAP सेटिंग',
    room_management : 'पाठ्यक्रम प्रबंधन',
    package_management : 'पैकेज प्रबंधन',
    category_management: 'श्रेणी प्रबंधन',
    logout : 'लोग आउट',
    ldap_details :'LDAP विवरण',
    domain :'डोमेन',
    base_dn :'बेस डी.एन.',
    url : 'यूआरएल',
    bind_cn :'बाँध सीएन',
    bind_password :'बाँध पासवर्ड',
    force_login:'सेना लॉग इन',
    new_category: 'नई श्रेणी',
    all_categories: 'सब वर्ग',
    category_details: 'श्रेणी विवरण',
    category_name: 'श्रेणी नाम',
    category_desc: 'वर्ग विवरण',
    category_list:'श्रेणी सूची',
    package_list:'पैकेज की सूची',
    room_list:'पाठ्यक्रम सूची',
    user_list:'उपयोगकर्ता सूची',
    corporate_detail:'कॉर्पोरेट विवरण',
    true: 'सच',
    false :'झूठा',
    conference :'सम्मेलन',
    lms:'एलएमएस',
    presenter : 'प्रस्तुतकर्ता',
    crm :'सीआरएम',
    admin : 'व्यवस्थापक',
    user :'उपयोगकर्ता',
    mix :'मिश्रण',
    forward :'आगे',
    hybrid :'संकर',
    no_users_found :'कोई उपयोग्कर्ता नहीं मिले',
    my_contacts:'मेरे संपर्क',
    chat :'बातचीत',
    mute_unmute:'म्यूट / अनम्यूट',
    disable_enable :'सक्षम अक्षम',
    start_recoding:'रिकॉर्डिंग शुरू',
    expand_contract:'विस्तार / अनुबंध',
    no_recent_contacts:'हाल ही के कोई संपर्क नहीं',
    add_your_contacts:'अपने संपर्क जोड़ें',
    close : 'बंद करे',
    sandra_smith: 'सैंड्रा स्मिथ',
    say_something:'आप कुछ बोलो',
    video_quality:'वीडियो की गुणवत्ता',
    languages : 'भाषा',
    help :'मदद',
    add_contacts :'संपर्क जोड़ें',
    attach_file:'फ़ाइल जोड़ें',
    search_contacts_add :'अपनी संपर्क सूची में जोड़ने के लिए संपर्क खोजें',
    set_language:'भाषा सेट करें',
    set_video_qulity :'सेट विडियो रेसोलुशन ',
    desc :'विवरण',
    push_the_message:'संदेश भेजें',
    invite_others:'दूसरों को तुरंत शामिल करने के लिए निमन्त्रण दे',
    regenerate : 'फिर से उत्पन्न करे',
    copy_this_link:'इस लिंक को कॉपी करे',
    share_Link:'लिंक शेयर करें',
    open_mail_client:'मेल क्लाइंट खोले',
    start_conference:'सम्मेलन प्रारंभ करें',
    create_new_room:'नया पाठ्यक्रम बनाएं',
    add_participants:'प्रतिभागियों को जोड़ें',
    search_room:'पाठ्यक्रम खोजें',
    my_rooms:'मेरे पाठ्यक्रम',
    select_your_room:'अपने पाठ्यक्रम को चुन ले',
    presenter_mode:'प्रस्तुतकर्ता मोड',
    conference_mode:'सम्मेलन मोड',
    valid_untill:'तब तक वैध',
    search_rooms:'पाठ्यक्रम खोजें...',
    schedules_new:'शेड्यूल नया',
    schedule_meeting:'सुनियोजित बैठक',
    past_schedules:'पिछले शेड्यूल',
    no_schedules:'कोई शेड्यूल नहीं',
    create_schedule:'अनुसूची वर्ग बटन पर क्लिक करके अपना शेड्यूल बनाएं',
    meeting_name : 'सभा का नाम',
    please_enter_meeting_name : 'कृपया मीटिंग का नाम दर्ज करें',
    create_edit_conference :'बनाएं / संपादित सम्मेलन',
    choose_anavailable_date :'एक उपलब्ध तिथि चुनें.',
    set_start_time:'प्रारंभ समय सेट करें',
    // set_end_time:'समाप्ति समय सेट करें',
    set_duration: 'सेट अवधि',
    recurring_schedule: 'आवर्ती कार्यक्रम',
    repeats: 'दोहराता',
    repeat_every: 'हर दोहराना',
    set_conference_password :'अपने सम्मेलन का पासवर्ड सेट करें',
    invite:'आमंत्रण',
    start : 'प्रारंभ',
    organizer :'व्यवस्थापक',
    edit_schedule:'इस शेड्यूल को संपादित करें',
    delete_schedule:'इस शेड्यूल को हटाएं',
    invite_contacts:'संपर्कों को आमंत्रित करें',
    invite_people :'लोगो को आमंत्रित करें',
    join_meeting:'अपने  डेस्कटॉप , टेबलेट  या  स्मार्टफोन  से  मेरी सभा में  शामिल  होने  की  कृपा करे ',
    conference_room_url :'निमंत्रण यूआरएल',
    enter_email:'ईमेल दर्ज करें',
    please_enter:'कृप्या ईमेल आईडी दर्ज करें',
    enter_meeting_name:'कृप्या कक्षा नाम दर्ज करें',
    select_room:'कृपया पाठ्यक्रम को चुन ले',
    minimum_date:'कृपया वर्तमान या भविष्य की तिथि का चयन करें',
    start_time_greater:'प्रारंभ समय वर्तमान समय की तुलना में अधिक होना चाहिए।',
    end_time_greater:'समाप्ति समय से अधिक समय शुरू होना चाहिए।',
    video_resolution:'SIF वीडियो रेसोलुशन के लिए',
    video_graphics:'वीडियो ग्राफिक्स ऐरे (वीजीए) के लिए वीडियो रेसोलुशन',
    hd_video : 'HD वीडियो रेसोलुशन के लिए',
    full_hd :'पूर्ण HD वीडियो रेसोलुशन के लिए',
    online:'ऑनलाइन',
    away:'दूर',
    offline:'ऑफलाइन',
    do_not_disturb:'परेशान न करें',
    logout:'लोग आउट',
    locale:'लोकले',
    time_zone:'समय क्षेत्र',
    date_format:'तारीख प्रारूप',
    time_format:'समय प्रारूप',
    currency_format: 'मुद्रा प्रारूप',
    prefered_language:'पसंदीदा भाषा',
    room_topic : 'विषय',
    my_topic :'मेरा विषय',
    room_topic_manager : 'पाठ्यक्रम विषय प्रबंधक',
    topic_name : 'विषय का नाम',
    description : 'विवरण',
    topic_details : 'विषय में जानकारी',
    upload : 'अपलोड',
    upload_file : 'दस्तावेज अपलोड करें',
    questionnaire: 'प्रश्नावली',
    all_questionnaire: 'सभी प्रश्नावली',
    questionnaire_list: 'प्रश्नावली सूची',
    add_questionnaire: 'प्रश्नावली जोड़े',
    questionnaire_details: 'प्रश्नावली में जानकारी',
    questionnaire_name: 'प्रश्नावली का नाम',
    view_questionnaire: 'देखें प्रश्नावली',
    questions: 'प्रशन',
    questionnaire_details: 'प्रश्नावली विवरण',
    title_questionnaire_details: 'नीचे आपके द्वारा बनाए गए प्रश्नावली के बारे में विवरण दिया गया है',
    selectroom:'पाठ्यक्रम को चुन ले',
    no_rooms:'कोई पाठ्यक्रम नहीं बनाया गया है',
    create_a_room : 'एक कोर्स बनाओ',
    requiedField:'कृपया',
    help_content:'सहायता सामग्री.',
    no_data_yet : 'अभी तक कोई डेटा नहीं है!',
    add_question: 'प्रश्न जोड़ें',
    title_question_details : 'नीचे इस प्रश्नावली में जोड़े गए सवाल हैं',
    deletefile : 'वर्तमान फ़ाइल हटाएँ',
    edit_questionnaire: 'प्रश्नावली संपादित करें',
    local_settings:'लोकले सेटिंग',
    edit_corporate :'संपादित कॉर्पोरेट',
    user_directory :'प्रयोक्ता निर्देशिका',
    new_corporate : "नया कॉर्पोरेट",
    all_packages : 'सभी पैकेज',
    package_directory : 'पैकेज निर्देशिका',
    new_package : 'नए पैकेज',
    edit_package : 'पैकेज को संपादित करें',
    room_directory : 'पाठ्यक्रम निर्देशिका',
    room_details : 'पाठ्यक्रम का विवरण',
    room_info :'पाठ्यक्रम जानकारी',
    category_directory : 'श्रेणी निर्देशिका',
    category_info :'श्रेणी जानकारी',
    smtp_info :'एसएमटीपी जानकारी',
    ldap_info:'एलडीएपी जानकारी',
    change_password : 'पासवर्ड बदलें',
    forgot_password : 'पासवर्ड भूल गए',
    reset_prompt : 'पासवर्ड रीसेट',
    forgot_prompt : 'कृपया अपना ईमेल पता दर्ज करें',
    invalid_date : 'कृपया वैध दिनांक चुनें / दर्ज करें',
    upload_url : 'URL अपलोड',
    multiple_delete : 'एकाधिक हटाएँ',
    select_gender:'लिंग चुनें',
    all_feedback:'सभी प्रतिक्रिया',
    feedback:'प्रतिक्रिया',
    user_feedback :'उपयोगकर्ता प्रतिसाद',
    room_feedback : 'फ़ीडबैक सूची',
    add_your_groups : 'अपने समूह जोड़ें',
    no_recent_groups : 'हाल के कोई समूह नहीं',
    back_to_room :'पाठ्यक्रम पर वापस',
    add_student : 'छात्र जोड़ें',
    instructor_name :'प्रशिक्षक का नाम',
    room_student_to_instructor : 'शिक्षक को छात्र जोड़ें',
    search_students :'छात्रों को खोजे ',
    my_groups :'मेरे समूह',
    no_recent_member : 'हाल के कोई सदस्य नहीं',
    add_your_members : 'अपने सदस्यों को जोड़ें',
    whiteboard:'व्हाइटबोर्ड',
    screen_share : 'स्क्रीन शेयर',
    hand_raise :'सवाल जवाब',
    topics:'विषय',
    topics_list: 'विषय सूची',
    welcome_room:'कोर्स में आपका स्वागत है:',
    fulltopic:'अधिक पढ़ें...',
    search_attendees:'उपस्थिति खोजें',
    no_topics_yet:'अभी तक कोई विषय नहीं!..',
    list_topics:'नीचे इस कमरे से संबंधित विषयों की सूची दी गई है।',
    have_schedule:'शेड्यूल है',
    your_selected_date:'आपके चयनित तिथियां',
    presenter:'प्रस्तुतकर्ता',
    telepresence:'टेलीप्रेसेन्स',
    record:'रिकॉर्ड करें',
    no_attendees_present:'कोई उपस्थित नहीं',
    no_user_added:'इस कोर्स में कोई उपयोगकर्ता जोड़ा नहीं गया',
    content:'सामग्री',
    files : 'फ़ाइलें',
    all : 'सब',
    image:'छवि',
    application :'आवेदन',
    video : 'वीडियो',
    audio :'ऑडियो',
    zip :'ज़िप',
    search :'खोज....',
    upload_media :'मीडिया अपलोड करें',
    upload_sco : 'SCO अपलोड करें',
    file_name : 'फ़ाइल का नाम',
    openfile : 'डाउनलोड',
    upload_list : 'अपलोड सूची',
    topic_list :'विषय सूची',
    dd_mm_yyyy :'DD/MM/YYYY',
    dd_mm_yy:'DD/MM/YY',
    ddmmyyyy:'DD-MM-YYYY',
    hh_mm_ss:'HH:MM:SS',
    usd:'USD',
    indian_rupee:'Indian Rupee',
    english :'English',
    hindi :'Hindi',
    french :'French',
    automatic : 'Automatic',
    set : 'Set',
    manage : 'प्रबंधन करें',
    room_chat : 'पाठ्यक्रम चैट',
    ask : 'पूछें',
    ask_question : 'प्रश्न पूछें',
    previous_questions : 'पिछले सवाल',
    post : 'प्रकाशित करें',
    no_questions : 'कोई प्रश्न नहीं',
    answers : 'जवाब',
    make_speaker : 'अनुरोध वीडियो',
    answer_the_question : 'प्रश्न का उत्तर दो',
    reply : 'जवाब देंs',
    your_comment : 'आपकी टिप्पणी',
    post_comment : 'टिप्पणी',
    previous_answers : 'पिछले जवाब',
    comment_on_answer : 'जवाब पर टिप्पणी',  
    make_this_user_the_speaker : 'इस अध्यक्ष को स्पीकर बनाओ',  
    delete_the_question : 'सवाल हटा दें',
    edit_the_question : 'सवाल संपादित',
    see_all_answers : 'सारे सवालों के जवाब  देखे',
    location : 'स्थान',
    room_chat : 'कोर्स चैट',
    no_questions : 'कोई प्रशन नहीं',
    ask : 'पूछना',
    topics_list: 'विषय सूची',
    media_resources :'मीडिया संसाधन',
    documents:'दस्तावेज़',
    questionnaires : 'प्रश्नावली',
    no_questionnaires_yet:'अभी तक कोई प्रश्नावली नहीं',
    start_date:'प्रारंभ तिथि',
    end_date:'अंतिम तिथि',
    choose_question_answers:'नीचे दिए गए सवालों के सही उत्तर चुनें',
    no_files_yet:'कोई फाइल नहीं!',
    no_questions_yet:'अभी तक कोई प्रशन नहीं!',
    not_attempted:'प्रयास नहीं किया!',
    room_location :'पाठ्यक्रम स्थान',
    add_college : 'कॉलेज जोड़ें',
    add_workplace : 'कार्यस्थल जोड़ें',
    add_highSchool : 'हाई स्कूल जोड़ें',
    add_professionalSkills : 'व्यावसायिक कौशल जोड़ें',
    work_title : 'काम',
    professionalSkills_title : 'व्यावसायिक कौशल',
    college_title : 'कॉलेज',
    highSchool_title : 'उच्च विद्यालय',
    work_education_timeperiod : 'समय सीमा',
    work_education_desciption : 'विवरण',
    work_education_graduated : 'स्नातक किया हुआ',
    work_education_school : 'स्कूल',
    work_education_concentration : 'एकाग्रता',
    work_education_company : 'कंपनी',
    work_education_position : 'पद',
    work_education_university : 'विश्वविद्यालय',
    work_education_workStatus : 'मैं वर्तमान में यहाँ काम करता हूं',
    work_education_saveChanges : 'परिवर्तनों को सुरक्षित करें',
    work_company_placeholder : 'आपने पहले कहां काम किया है?',
    work_position_placeholder : 'अपकी नौकरी शीर्षक क्या है?',
    college_university_placeholder : 'आपने कौन सी कॉलेज / विश्वविद्यालय में भाग लिया?',
    school_placeholder : 'आपने किस स्कूल में भाग लिया?',
    title_questionnaire_assigned:'नीचे दिए गए प्रश्नावली इस विषय पर दी गई हैं',
    assign_questionnaire : 'प्रश्नावली असाइन करें',
    add_feedback : 'फ़ीडबैक जोड़ें',
    course_location : 'कोर्स स्थान',
    title_location_details :'नीचे इस पाठ्यक्रम में जोड़े गए स्थान हैं',
    all_locations:'सभी स्थान',
    location_directory :'स्थान निर्देशिका',
    new_location:'नया स्थान',
    location_info : 'स्थान जानकारी',
    location_name : 'स्थान का नाम',
    location_details : 'स्थान के विवरण',
    location_list : 'स्थान सूची',
    title_created_location_details : 'नीचे आपके द्वारा बनाए गए स्थान के बारे में विवरण दिया गया है।',
    edit_location : 'स्थान संपादित करें',
    locale_directory:'स्थानीय निर्देशिका',
    share_your_screen :'अपनी स्क्रीन शेयर करें!',
    city_town : 'शहर / नगर',
    landmark : 'महत्वपूर्ण स्थान के पास',
    contact_information : 'संपर्क जानकारी',
    website_and_social_links : 'वेबसाइट और सामाजिक लिंक',
    basic_information : 'मूलभूत जानकारी',
    add_address : 'पता जोड़ें',
    add_website : 'वेबसाइट जोड़ें',
    add_social_link : 'सामाजिक लिंक जोड़ें',
    add_basic_information : 'बुनियादी जानकारी जोड़ें',
    social_link : 'सामाजिक लिंक',
    birthday : 'जन्मदिन',
    save_changes : 'परिवर्तनों को सुरक्षित करें',
    birth_year : 'जन्म वर्ष',
    add_a_social_links : 'सामाजिक लिंक',
    locale_directory:'स्थानीय निर्देशिका',
    viewprofile : 'प्रोफाइल देखिये',
    profile : 'प्रोफाइल',
    back : 'पिछली तरफ़',
    sync : 'सिंक',
    pointer: 'सूचक',
    pencil:'पेंसिल',
    square : 'चौकोर',
    circle :'वृत्त',
    oval :'ओवल',
    line :'लाइन',
    alphabets :'अल्फाबेट्स ',
    erase_all :'सब मिटा दो',
    fill_background_colors:'बैकग्राउंड रंग भरें',
    background:'बैकग्राउंड',
    stroke:'स्ट्रोक ',
    line_color:'लाइन रंग',
    no_participants:'कोई प्रतिभागी नहीं',
    no_conference_loaded:'कोई सम्मेलन लोड नहीं हुआ ...',
    loading:'लोड हो रहा है',
    loading_please_wait:'लोड हो रहा है! कृपया प्रतीक्षा करें',
    current_password : 'वर्तमान पासवर्ड',
    new_password : 'नया पासवर्ड',
    retype_new_password : 'नया पासवर्ड दोबारा टाइप करें',
    please_provide_your_valuable_feedback : 'कृपया अपने बहुमूल्य फ़ीडबैक प्रदान करें',
    video_quality : 'वीडियो की गुणवत्ता',
    rate_the_quality_of_the_video_you_experienced : 'आपके द्वारा अनुभवी वीडियो की गुणवत्ता का मूल्यांकन करें',
    audio_quality : 'ध्वनि गुणवत्ता',
    rate_the_quality_of_the_audio_you_experienced : 'आपको अनुभव की गई सामग्री साझा करने की गुणवत्ता का मूल्यांकन करें',
    content_sharing : 'सामग्री शेयरिंग',
    rate_the_quality_of_the_content_sharing_you_experienced : 'आपको अनुभव की गई सामग्री साझा करने की गुणवत्ता का मूल्यांकन करें',
    knowlegeable_session : 'जानकार सत्र',
    rate_how_Knowlegeable_this_session_was : 'इस सत्र के बारे में जानने योग्य कैसे क्रेडेंशियल',
    instructor_skills : 'प्रशिक्षक कौशल',
    rate_how_good_instructor_presented_the_subject : 'रेट कैसे अच्छा प्रशिक्षक विषय प्रस्तुत किया',
    overall_rating : 'समग्र रेटिंग',
    provide_the_overall_rating : 'समग्र रेटिंग प्रदान क्रेडेंशियल',
    your_comments : 'आपकी टिप्पणी',
    your_comments_are_highly_appreciated : 'आपकी टिप्पणियों की अत्यधिक सराहना की जाती है',
    no_thanks : 'जी नहीं, धन्यवाद',
    poor : 'खराब',
    average : 'औसत',
    good : 'अच्छा',
    very_good : 'बहुत अच्छा',
    excellent : 'उत्कृष्ट',
    feedback_submit : 'जमा करें',
    become_host_to_access_bellow_features :'ब्रश सुविधाओं को एक्सेस करने के लिए होस्ट बनें',
    screen_shared:'स्क्रीन शेयर्ड!',
    you_are_sharing_your_screen:'आप अपनी स्क्रीन शेयर कर रहे हैं!',
    ok : 'ठीक है ',
    warning:'चेतावनी',
    delete_question_alert:'क्या आप सुनिश्चित हैं कि आप प्रश्न को हटाना चाहते हैं?',
    delete_category_alert:'क्या आप सुनिश्चित हैं कि आप श्रेणी को हटाना चाहते हैं?',
    delete_corporate_alert:'क्या आप सुनिश्चित हैं कि आप कॉर्पोरेट को हटाना चाहते हैं?',
    delete_location_alert:'क्या आप सुनिश्चित हैं कि आप स्थान को हटाना चाहते हैं?',
    delete_package_alert:'क्या आप सुनिश्चित हैं कि आप पैकेज को हटाना चाहते हैं?',
    delete_address_alert:'क्या आप सुनिश्चित हैं कि आप पता हटाना चाहते हैं?',
    delete_link_alert:'क्या आप सुनिश्चित हैं कि आप वेबसाइट लिंक को हटाना चाहते हैं?',
    delete_social_link_alert:'क्या आप सुनिश्चित हैं कि आप सामाजिक लिंक को हटाना चाहते हैं?',
    delete_birth_day_alert:'क्या आप सुनिश्चित हैं कि आप जन्मदिन को हटाना चाहते हैं?',
    delete_gender_alert:'क्या आप सुनिश्चित हैं कि आप लिंग को हटाना चाहते हैं?',
    delete_school_alert: 'क्या आप सुनिश्चित हैं कि आप स्कूल को हटाना चाहते हैं?',
    delete_college_alert: 'क्या आप सुनिश्चित हैं कि आप कॉलेज को हटाना चाहते हैं?',
    delete_workplace_alert: 'क्या आप सुनिश्चित हैं कि आप कार्यस्थल को हटाना चाहते हैं?',
    delete_professional_alert: 'क्या आप सुनिश्चित हैं कि आप व्यावसायिक कौशल को हटाना चाहते हैं?',
    delete_user_alert : 'क्या आप सुनिश्चित हैं कि आप उपयोगकर्ता को हटाना चाहते हैं?',
    delete_room_alert : 'क्या आप सुनिश्चित हैं कि आप पाठ्यक्रम को हटाना चाहते हैं?',
    delete_topic_alert : 'क्या आप सुनिश्चित हैं कि आप विषय को हटाना चाहते हैं?',
    delete_file_alert : 'क्या आप सुनिश्चित हैं कि आप फाइल को हटाना चाहते हैं?',
    delete_all_files_alert : 'क्या आप सुनिश्चित हैं कि आपको ये सारी फाइल्स को हटाना चाहते हैं?',
    delete_questionaire_alert : 'क्या आप सुनिश्चित हैं कि आपको ये सारी प्रश्नावली को हटाना चाहते हैं?',
    delete_schedule_alert : 'क्या आप सुनिश्चित हैं कि आप शेड्यूल को हटाना चाहते हैं?',
    edit_schedule_alert : 'यदि आप शेड्यूल को संपादित करते हैं तो निमंत्रण लिंक को फिर से भेजने की आवश्यकता है क्या आप वास्तव में संपादित करना चाहते हैं?',
    delete_whiteboardObjects_alert : 'क्या आप सुनिश्चित हैं कि आप हटाना चाहते हैं?',
    logout_confirm_incall : 'आप कॉल में हैं, क्या आप सुनिश्चित हैं कि आप लॉग आउट करना चाहते हैं?',
    author:'रचयिता',
    selected_codec:'चुना हुआ कोडेक',
    start_time:'शुरू समय',
    end_time:'अंतिम समय',
    delete_room_user_alert:'क्या आप सुनिश्चित हैं कि आप उपयोगकर्ता को हटाना चाहते हैं?',
    chat_file_alert:'फ़ाइल का आकार 20MB से कम होना चाहिए!..',
    share_file_alert:'फ़ाइल का आकार 10MB से कम होना चाहिए!..',
    topic_file_alert:'फ़ाइल का आकार 20MB से कम होना चाहिए!..',
    url_alert:'एक URL दर्ज करें!..',
    valid_url_alert :'वैध URL नहीं!..',
    unassign_question_alert:'क्या आप सुनिश्चित हैं कि आप प्रश्नावली को अनसिनित करना चाहते हैं?',
    generate_meeting_alert:'इस कोर्स के लिए पहले से ही निर्धारित मीटिंग्स क्या आप दोबारा राज करना चाहते हैं?',
    questionnaire_alert:'प्रश्नावली अभी तक शुरू नहीं हुई!..',
    delete_group_alert:'क्या आप सुनिश्चित हैं कि आप समूह को हटाना चाहते हैं?',
    delete_member_group_alert:'क्या आप सुनिश्चित हैं कि आप समूह के सदस्य को हटाना चाहते हैं?',
    submitted_by : 'द्वारा प्रस्तुत',
    user_name : 'उपयोगकर्ता नाम',
    over_all_rating : 'समग्र रेटिंग',   
    knowlegable_session: 'जानकार सत्र',           
    user_comment : 'उपयोगकर्ता टिप्पणी',    
    user_feedback_data : 'प्रतिक्रिया',
    individual_feedback : 'उपयोगकर्ता द्वारा सबमिट किए गए फ़ीडबैक विवरण',
    feedback_details : 'व्यक्तिगत फ़ीडबैक विवरण',
    feedback_submitted_successfully : 'सफलतापूर्वक सबमिट की गई प्रतिक्रिया',
    submitted : 'प्रस्तुत',
    edit_question: 'प्रश्न संपादित करें',
    question:'प्रश्न',
    type :'प्रकार',
    mark_correct_answer:'दो जवाब विकल्पों को दर्ज करें और सही उत्तर दर्ज करें',
    select_type:'प्रकार चुनें',
    remove:'हटाना',
    answer_choice:'उत्तर विकल्प',
    delete_this_location:'इस स्थान को हटा दें',
    no_locations_yet:'अभी तक कोई स्थान नहीं!!!',
    enter_the_answer_choices_and_mark_which_answer_is_correct:'उत्तर के विकल्प दर्ज करें, और चिह्नित करें कि कौन सा उत्तर सही है',
    transport_title : 'ट्रांसपोर्ट?',
    uploadtotopic_title : 'इस विषय में फाइल अपलोड करने के लिए सामग्री प्रकार चुनें',
    file_title : 'फ़ाइलें',
    media_title : 'मीडिया',
    sco_title : 'ज़िप',
    youtube_url_title : 'यूट्यूब यूआरएल:',
    upload_title : 'अपलोड करें',
    filetypes_title: 'फाइल के प्रकार :',
    youtube_url_placeholder : 'पेस्ट करें लिंक यहाँ जैसे: https://www.youtube.com/channel/UCdPJhu2eYCXIDo5hcTDw0_g',
    candidate_name : 'प्रत्याशी का नाम',
    questionnaire_result : 'परिणाम',
    result_details : 'परिणाम विवरण',
    result_list : 'परिणाम सूची',
    answer_sheet:'उत्तर पत्रिका',
    answer_sheet_details:'उत्तर पत्र विवरण',
    grade:'ग्रेड',
    open:'खुला',
    close:'बंद करे',
    select_location:'स्थान चुनें',
    remove_user_from_room:'कोर्स से उपयोगकर्ता को निकालें',
    add_user:'उपयोगकर्ता जोड़ें',
    add_student:'छात्र जोड़ें',
    view_students:'छात्र देखें',
    list_results:'सूची परिणाम',
    view_edit_questionaire_from_topic:'विषय से प्रश्नावली देखें / संपादित करें',
    unassign_questionnaire_from_topic:'विषय से प्रश्नावली अनियंत्रित करें',
    remove_question_from_questionnaire:'प्रश्नावली से प्रश्न निकालें',
    view_edit_question_from_questionnaire:'प्रश्नावली से प्रश्न देखें / संपादित करें',
    participants_group:'प्रतिभागी समूह',
    participants_list : 'छात्रों की सूची',
    enter_group_name : 'समूह नाम दर्ज करें',
    not_allowed:'अनुमति नहीं हैं',
    no_questions_added_to_this_questionnaire:'इस प्रश्नावली में कोई प्रश्न नहीं जोड़ा गया',
    feature_info : 'सुविधा जानकारी',
    features : 'विशेषताएं',
    no_of_rooms : 'पाठ्यक्रमों की संख्या',
    no_of_topics : 'विषयों की संख्या',
    server_recording : 'सर्वर रिकॉर्डिंग',
    client_recording : 'क्लाइंट रिकॉर्डिंग',
    video_conference : 'वीडियो सम्मेलन',
    continuous_presence : 'सतत उपस्थिति की संख्या',
    edit_group_name : 'समूह का नाम संपादित करें',
    add_participants_group : 'छात्रों को समूह में जोड़ें',
    search_participants : 'खोज छात्रों',
    delete_participant_alert : 'क्या आप इस छात्र को निकालना चाहते हैं?',
    group_name : 'समूह का नाम',
    created_by : 'द्वारा बनाई गई',
    group_participants : 'छात्र सूची',
    title_groupParticipants_details : 'नीचे इस समूह में छात्रों को जोड़ा गया है',
    please_enter_group_name : 'समूह का नाम रिक्त नहीं हो सकताs',
    please_enter_participant_name : 'कृपया छात्र का चयन करें',
    participants_group_list : 'प्रतिभागी समूह सूची',
    room_configuration : 'पाठ्यक्रम कॉन्फ़िगरेशन',
    configure_feedback : 'प्रतिक्रिया कॉन्फ़िगर करें',
    configration : 'विन्यास',
    feedbackType_title : 'प्रतिक्रिया के प्रकार',
    codecType_title : 'कोडेक प्रकार',
    enableLive_title : 'लाइव सक्षम करें',
    assign_questionaire : 'प्रश्नावली असाइन करें',
    delete_SMTPSettings_alert:'क्या आप वाकई इस SMTP सेटिंग को हटाना चाहते हैं?',
    time_limit : 'समय सीमा',
    no_time_limitations : 'कोई समय सीमाएं नहीं',
    delete_LDAPSettings_alert:'क्या आप वाकई इस LDAP सेटिंग को हटाना चाहते हैं?',
    previous:'पिछला',
    next: 'अगला',
    enable_swot : 'स्वाॉट सक्षम करें',
    select_an_answer_otherwise_it_will_not_be_considered_for_evaluation : 'एक जवाब चुनें, अन्यथा इसे मूल्यांकन के लिए नहीं माना जाएगा',
    back_to_uploadlist :'अपलोड सूची पर वापस जाएं',
    no_users_found:'कोई उपयोगकर्ता नहीं मिला',
    select_role :'भूमिका का चयन करें',
    
    createdby:'के द्वारा बनाई गई',
    count:'कुल',
    please_enter_the_question:'कृपया प्रश्न दर्ज करें',
    invalid_mail_id:'अमान्य मेल आईडी',
    accept:'स्वीकार',
    reject:'अस्वीकार',
    request_pending:'अनुरोध अपूर्ण है',
    start_chating:'चाट शुरू करो ....',
    export_users: 'उपयोगकर्ताओं को निर्यात करें',
    import_users: 'उपयोगकर्ताओं को आयात करें',
    import_format: 'आयात प्रारूप',
    pdf_view: 'पीडीएफ देखें',
    uploading_please_wait : 'अपलोड हो रहा है! कृपया प्रतीक्षा करें',
    host_access : 'होस्ट प्रवेश',
    become_host :'होस्ट बनें',
    become_a_host: 'होस्ट बनें',
    request_access_share: 'स्क्रीन / दस्तावेज़ साझा करने के लिए अभिगम का अनुरोध',
    revoke : 'वापस लेना',
    enter_host_password : 'होस्ट पासवर्ड दर्ज करें',
    host_error : 'गलत होस्ट पासवर्ड, कृपया पुनः प्रयास करें',
    revoke_error : 'आप पहले से ही होस्ट हैं क्या आप निरस्त करना चाहते हैं ...?',
    delete_this_group : 'इस समूह की याचिका को हटा दें',
    remove_participants_from_group : 'समूह से छात्र को हटा दें',
    confirm_password : 'पासवर्ड की पुष्टि करें',
    no_data_found : 'कोई डेटा नहीं मिला',
    invalid_group_name : 'अमान्य समूह का नाम',
    no_groups_found : 'कोई ग्रुप्स नहीं मिलें',
    select_language:'भाषा चुनिए',
    no_data_found : 'कोई डेटा नहीं मिला',
    start_class : 'कक्षा प्रारंभ करें',
    join_class : 'कक्षा में शामिल हों',
    create_a_class : 'अनुसूची वर्ग',
    upcoming_classes : 'आगामी अनुसूची',
    past_classes : 'पिछली अनुसूची',
    have_class : 'पहले से ही एक अनुसूची है',
    create_edit_class :'कक्षा बनाएं / संपादित करें',
    class_name : 'कक्षा का नाम',
    please_enter_class_name : 'कृपया वर्ग का नाम दर्ज करें',
    my_classes : 'मेरी कक्षाएं',
    set_class_password :'अपना क्लास पासवर्ड सेट करें',
    edit_class:'इस कक्षा को संपादित करें',
    delete_class :'इस कक्षा को हटाएं',
    edit_class_alert : 'यदि आप कक्षा को संपादित करते हैं तो निमंत्रण लिंक को फिर से भेजा जाना चाहिए। क्या आप वास्तव में संपादित करना चाहते हैं?',
    delete_class_alert : 'क्या आप वाकई इस कक्षा को हटाना चाहते हैं?',
    set_desc : 'विवरण सेट करें',
    submitted_on : 'सबमिट करने की तारीख',
    room_options : 'कक्षा विकल्प',
    select:'चयन',
    file:'फ़ाइल',
    add_topics : 'पाठ्यक्रम को विषय जोड़ें',
    room_assignments : 'कार्य',
    assignment_list : 'कार्य सूची',
    assignment_details : 'कार्य जानकारी',
    assignment_name : 'कार्य का नाम',
    room_assignment_manager :'पाठ्यक्रम कार्य प्रबंधक',
    list_assignments: 'इस कोर्स से संबंधित कार्य की सूची नीचे दी गई है',
    no_assignments_yet:'अभी तक कोई कार्य नहीं है!..',
    submissions: 'प्रस्तुतियाँ',
    submission_list: 'प्रस्तुत सूची',
    student_name: 'छात्र का नाम',
    back_to_assignments: 'वापस कार्य पर',
    become_host_to_share_your_document :'अपने दस्तावेज़ को साझा करने के लिए होस्ट बनें',
    share_your_document :'अपनी दस्तावेज़ साझा करें!',
    share_your_screen_document: 'अपनी स्क्रीन / दस्तावेज़ साझा करें!',
    room_feedback_title : 'प्रतिक्रिया',
    manage_assignments : 'कार्य प्रबंधित करें',
    manage_questionnaire : 'प्रश्नावली प्रबंधित करें',
    plagiarism: 'साहित्यिक चोरी',
    drag: 'खींचें',
    delete_assignment_alert : 'सभी सबमिशन भी हटा दिए जाएंगे, क्या आप वाकई यह कार्य हटाना चाहते हैं?',
    refresh_schedules:'रीफ्रेश अनुसूचियों',
    schedules : 'अनुसूचियों',
    refresh_rooms :'रीफ्रेश पाठ्यक्रम',
    creating_please_wait : 'बना रहे हैं! कृपया प्रतीक्षा करें',
    updating_please_wait : 'अद्यतन कर रहे हैं! कृपया प्रतीक्षा करें',
    enable:'सक्षम',
    publish:'प्रकाशित करना',
    categories: 'श्रेणियाँ है.',
    corporates :'कॉरपोरेट्स है.',
    feedbacks:'प्रतिक्रिया है.',
    locations : 'स्थानों है.',
    packages : 'पैकेजेस है.',
    participants : 'समूह में भाग लेने वाले',
    rooms : 'पाठ्यक्रम है.',
    users : 'उपयोगकर्ताओं है.',
    list_topic : 'विषय है.',
    list_files : 'फ़ाइलें है.',
    list_certificates : 'प्रमाणपत्रों की है.',
    results : 'परिणाम है.',
    polls : 'सर्वेक्षण',
    poll_list : 'सर्वेक्षण सूची',
    list_polls: 'इस कमरे से संबंधित सर्वेक्षण की सूची नीचे दी गई है।',
    no_polls_yet: 'अभी तक कोई सर्वेक्षण नहीं! ..',
    package_validFrom : 'से वैध',
    create_poll : 'सर्वेक्षण बनाएं',
    option : 'विकल्प',
    package_validFrom : 'से वैध',
    published : 'प्रकाशित',
    publish : 'प्रकाशित करना',
    update_poll : 'सर्वेक्षण अद्यतन करें',
    delete_poll_alert : 'क्या आप वाकई इस सर्वेक्षण को हटाना चाहते हैं?',
    delete_poll : 'मतदान हटाएं',
    broadcast : 'समाचार प्रसारण',
    broadcast_news_list : 'प्रसारण समाचार सूची',
    no_broadcast : 'कोई प्रसारण समाचार नहीं',
    broadcast_list : 'प्रसारण सूची',
    delete_poll : 'सर्वेक्षण हटाएं',
    no_submittions_yet: 'अभी तक कोई प्रस्तुतियाँ नहीं है!..',
    list_poll_submissions : 'नीचे इस सर्वेक्षण से संबंधित प्रस्तुतियाँ की सूची है।',
    poll_analysis : 'नीचे इस सर्वेक्षण से संबंधित विश्लेषण चार्ट है',
    delete_broadcast_alert:'क्या आप वाकई इस प्रसारण समाचार को हटाना चाहते हैं?',
    view_comments : 'टिप्पणियाँ',
    view_all_comments : 'सभी टिप्पणियां देखें',
    edit_comment : 'टिप्पणी संपादित करें',
    delete_comment : 'टिप्पणी निकालें',
    reply_on_comment : 'टिप्पणी पर उत्तर दें',
    reply_comment : 'जवाब दें',
    previous_comments : 'पिछली टिप्पणी',
    comment_on_broadcast_news : 'प्रसारण समाचार पर टिप्पणी',
    your_reply : "टिप्पणी पर उत्तर दें",
    delete_broadcast_alert:'क्या आप वाकई इस प्रसारण को हटाना चाहते हैं?',
    refresh_polls : 'रीफ्रेश सर्वेक्षण',
    request_for_share_document : 'शेयर स्क्रीन / दस्तावेज़ के लिए अनुरोध',
    studentId : 'छात्र आईडी',
    view_result : 'परिणाम देखें',
    submit_poll : 'सर्वेक्षण जमा करें',
    attendance : 'उपस्थिति',
    please_enter_the_broadcast : 'कृपया प्रसारण समाचार दर्ज करें',
    total_attendance: 'कुल उपस्थिति',
    student_list: 'छात्र सूची',
    class_list: 'कक्षा सूची',
    attendance : 'उपस्थिति',
    expiry_Date : 'समाप्ति तिथि',
    students: 'students',
    overall: 'OverAll',
    detailed: 'Detailed',
    classes: 'classes',
    view_attendance:'उपस्थिति देखें',
    assignment_reports:'असाइनमेंट रिपोर्ट',
    assignment_list:'असाइनमेंट सूची',
    my_reports:'मेरी रिपोर्ट',
    created_date:'रचना तिथि',
    expiry_date :'समाप्ति तिथि' ,
    assignment: 'असाइनमेंट',
    test_reports: 'जाँच रिपोर्ट',
    active_users: 'सक्रिय उपयोगकर्ता',
    invalid_enddate : 'अमान्य समाप्ति तिथि',
    select_the_days : 'कृपया दिन चुनें',
    select_the_endson : 'कृपया समाप्त होने का चयन करें',
    select_occurence : 'कृपया नंबर दर्ज करें घटनाओं की',
    current_day : 'वर्तमान दिन',
    recurring : 'आवर्ती',
    current_recurring : 'वर्तमान दिन / पुनरावर्ती हटाएं',
    delete_current_recurring : 'क्या आप वर्तमान दिन (या) पुनरावर्ती शेड्यूल को हटाना चाहते हैं?',
    title_user_details:'नीचे आपके द्वारा बनाए गए उपयोगकर्ता के विवरण दिए गए हैं',
    registration_prompt:'कृपया पंजीकरण के लिए नीचे फ़ील्ड भरें',
    institute_name: 'कृपया संस्थान नाम दर्ज करें',
    please_enter_institute_name : 'कृपया संस्थान नाम दर्ज करें',
    inactive_user : 'पंजीकृत उपयोगकर्ता',
    activate_user : 'सक्रिय उपयोगकर्ता',
    active_user : 'सक्रिय उपयोगकर्ता',
    inactive_user_list : 'सक्रिय उपयोगकर्ता सूची में',
    Marks : 'अंक',
    total_marks : 'कुल अंक',
    multiple_choice_answers : 'एकाधिक विकल्प जवाब',
    multiple_responsive_answers : 'एकाधिक उत्तरदायी उत्तर',
    true_false : 'हां या नहीं जवाब', 
    active_users_list :'सक्रिय उपयोगकर्ता सूची',
    course_attendance : 'कोर्स की उपस्थिति',
    true_false : 'हां या नहीं जवाब',
    show_result : 'परिणाम दिखाओ',
    true_false : 'हां या नहीं जवाब',  
    student_reg_form : 'छात्र पंजीकरण फॉर्म',
    already_registered_user : 'पहले से पंजीकृत उपयोगकर्ता?',
    i_agree : 'मैं सहमत हूं',
    terms_conditions : 'नियम और शर्तें',
    grade_configuration : 'ग्रेड कॉन्फ़िगरेशन',
    title_grade_configuration : 'प्रश्नावली ग्रेड को यहां कॉन्फ़िगर करें.',
    title_view_grade_configuration : 'नीचे दिए गए ग्रेड हैं जो प्रश्नावली परिणाम में दिखाई देंगे।',
    fullcalender : 'पूर्ण कैलेंडर',
    select_duration : 'प्लस अवधि का चयन करें',
    set_hours : 'सेट घंटे',
    set_minutes : 'सेट मिनट',
    checkin_time : 'प्रवेश का समय',
    checkout_time : 'जाने का समय',
    topic_report : 'विषय रिपोर्ट ',
    course_view : 'पाठ्यक्रम देखें',
    topic_name : 'विषय का नाम',
    viewed_topics : 'देखा गया विषय',
    topic_viewed_users : 'विषय देखें उपयोगकर्ता',
    description : 'विवरण',
    status : 'स्थिति',
    deleted_user : 'हटाया हुआ उपयोगकर्ता',
    active : 'सक्रिय',
    registered : 'दर्ज कराई',
    deleted : 'हटाए गए',
    deleted_list : 'हटाए गए उपयोगकर्ता',
    active_user_list : 'सक्रिय उपयोगकर्ता',
    registered_user_list : 'पंजीकृत उपभोक्ता',
    skip:'छोड़ें',
    all_participants_groups: 'सभी प्रतिभागी समूह',
    from : 'से',
    to : 'तक',
    no_replies : 'जवाब नहीं',
    no_answers :'कोई जवाब नहीं',
    summary : 'सारांश',
    link_is_either_expired_or_broken:'लिंक या तो समाप्त हो या टूटा हुआ है',
    room_students : 'पाठ्यक्रम के छात्रों',
    topic_content : 'विषय सामग्री',
    you_are_in_mange_users_panel:'आप उपयोगकर्ता पैनल प्रबंधित कर रहे हैं',
    work_edu_details:'कार्य और शिक्षा देखें',
    view_contact_details:'संपर्क देखें',
    view_locale:'लोकले देखें',
    you_are_in_active_users_panel : 'आप सक्रिय उपयोगकर्ता पैनल में हैं',
    you_are_in_my_profile_panel : 'आप मेरे खाते के पैनल में हैं',
    you_are_in_package_list_panel : 'आप पैकेज प्रबंधन पैनल में हैं',
    you_are_in_corporate_list_panel : 'आप कॉर्पोरेट पैनल में हैं',
    you_are_in_category_list_panel : 'आप श्रेणी प्रबंधन पैनल में हैं',
    you_are_in_room_list_panel :'आप कोर्स प्रबंधन पैनल में हैं',
    you_are_in_location_list_panel : 'आप स्थान पैनल में हैं',
    you_are_in_participant_group_list_panel :'आप प्रतिभागी समूह पैनल में हैं',
    you_are_in_questionarie_list_panel : 'आप प्रश्नावली पैनल में हैं',
    edit_grade_configuaration : 'ग्रेड कॉन्फिगरेशन संपादित करें',
    You_are_in_reports_list_panel : 'आप रिपोर्ट पैनल में हैं',
    add_assignment:'असाइनमेंट जोड़ें',
    attendance_reports : 'उपस्थिति रिपोर्टें',
    users_activity : 'उपयोगकर्ता गतिविधि',
    Update : "संपादित करें",
    blocked: 'अवरोधित',
    guest: 'अतिथि',
    requiedFieldText : 'कृपया दर्ज करें',
    requiedFieldDate : 'कृपया चुने',
    validInputData : 'कृपया वैध दर्ज करें',
    select_dropdown : 'चुने',
    save_publish:'बचाना & प्रकाशित करना',
    requested_for_share_document_please_wait : 'शेयर स्क्रीन / दस्तावेज़ के लिए अनुरोध किया, कृपया प्रतीक्षा करें .....',
    confirm_unassign_questionnaire_topics : 'क्या आप वाकई प्रश्नावली को अनसाइंड करना चाहते हैं क्योंकि इस प्रश्नावली के आधार पर परिणाम हैं?',
    connect_with_social_link:'सामाजिक लिंक से जुड़ें',
    requested_for_share_document_please_wait : 'शेयर स्क्रीन / दस्तावेज़ के लिए अनुरोध किया, कृपया प्रतीक्षा करें .....',
    update_publish : 'संपादित & प्रकाशित करना',
    invalid_file_format : 'अमान्य फाइल प्रारूप',
    confirm_delete_question_from_questionnaire : 'क्या आप प्रश्नावली से प्रश्न हटाना चाहते हैं क्योंकि प्रश्न के आधार पर परिणाम होते हैं?',
    stop_screen_share: 'स्क्रीन शेयर बंद करें',
    pause_screen_share: 'स्क्रीन शेयर रोकें',
    play_screen_share: 'स्क्रीन साझा प्ले करें',
    add_students : 'छात्र जोड़ें',
    confirm_submit_alert : 'क्या आप वाकई सबमिट करने के इच्छुक हैं?',
    user_reg_form : 'उपयोगकर्ता पंजीकरण फॉर्म',
    registration_please_wait : 'पंजीकरण कर रहा है, कृपया प्रतीक्षा करें',
    student_data_not_found : 'छात्र डेटा नहीं मिला',
    individual_user : 'व्यक्तिगत उपयोगकर्ता',
    group : 'समूह',
    add_groups:'समूह जोड़ें',
    edit_room : 'कोर्स संपादित करें',
    edit_profie :'प्रोफाइल संपादित करें',
    create_topic:'विषय बनाएँ',
    new_questionnaire:'नई प्रश्नावली',
    student_assignment_list_title : 'आपके द्वारा सबमिट किए गए कार्य',
    evaluation_not_yet_done :  'मूल्यांकन अभी तक नहीं किया',
    instructor_feedback : "प्रशिक्षक का फीडबैक",
    total_assignment_marks: 'कुल असाइनमेंट मार्क्स',
    scored_marks : 'स्कोरांकित मार्क्स',
    add_another_field : 'अन्य फ़ील्ड जोड़ें',
    maximum_marks : 'अधिकतम अंक',
    total_score : 'कुल स्कोर',
    load_more:'और लोड करें..',
    note : 'टिप्पणी',
    default:'पूर्व निर्धारित',
    proxy:'प्रतिनिधि',
    quality : 'गुणवत्ता',
    best_quality:'सर्वोत्तम गुणवत्ता',
    better_quality:'बेहतर गुणवत्ता',
    standard:'मानक',
    better_speed:'बेहतर गति',
    best_speed:'सर्वोत्तम गति',
    ends_on:'समाप्त होता है',
    after :'बाद',
    occurences:'घटनाओं',
    repeat_on:'दोबारा चालू',
    On : 'चालू',
    No_Questionnaires_assigned_to_this_topic:'इस विषय को सौंपा कोई प्रश्नावली नहीं',
    total_percentage : 'कुल प्रतिशत',
    options : 'विकल्प',
    revoke_host:'मेजबान रद्द करें',
    become_host:'मेजबान बनें',
    video_settings:'वीडियो सेटिंग्स',
    mute_unmute:'म्यूट / अनम्यूट',
    remote_mute_unmute : 'रिमोट म्यूट / अनम्यूट',
    full_Screen:'पूर्ण स्क्रीन',
    share : 'शेयर',
    volume_on_off:'वॉल्यूम चालू / बंद',
    become_speaker:'स्पीकर बनें',
    revoke_speaker : 'स्पीकर रद्द करें',
    become_presenter : 'प्रस्तुतकर्ता बनें',
    revoke_presenter:'प्रस्तुतकर्ता को रद्द करना',
    add_another_field: 'अन्य फ़ील्ड जोड़ें',
    today : 'आज',
    yesterday: 'बिता कल',
    last_seven_days: 'पिछले 7 दिन',
    last_thirty_days: 'पिछले 30 दिनों में',
    custom: 'रिवाज',
    date_range: 'तिथि सीमा',
    apply: 'लागू करें',
    not_loggedin_users : 'लॉग-इन नहीं हुए उपयोगकर्ता',
    loggedin_users: 'लॉग-इन उपयोगकर्ता',
    loggedin_users_status: 'लॉग-इन उपयोगकर्ता स्थिति',
    present_instructors: 'वर्तमान प्रशिक्षक',
    absent_instructors: 'अनुपस्थित प्रशिक्षक',
    present_students:'वर्तमान छात्र',
    absent_students:'अनुपस्थित छात्र ',
    instructors_attendance: 'प्रशिक्षक उपस्थिति',
    students_attendance: 'छात्र उपस्थिति',
    percentage : 'प्रतिशत',
    offline_visits: 'ऑफ़लाइन विज़िट्स',
    online_visits: 'ऑनलाइन विज़िट्स',
    absent_schedules: 'अनुपस्थित अनुसूचियां',
    total_schedules: 'कुल अनुसूची',
    total_attendance: 'कुल उपस्थिति',
    count: 'गिनती',
    back_to_list: 'दोबारा सूची को जाएं',
    back_to_reports: 'रिपोर्ट पर वापस जाएं',
    completely_viewed_topic_users: 'पूरी तरह से देखा गया विषय उपयोगकर्ता',
    partially_viewed_topic_users: 'आंशिक रूप से देखा गया विषय उपयोगकर्ता',
    not_AtAll_Viewed_Topic_Users: 'सभी दृश्यमान विषय उपयोगकर्ताओं में नहीं',
    viewed_users : 'देखे गए उपयोगकर्ता',
    completely_viewed_topics: 'पूरी तरह से देखा गया विषय',
    partially_viewed_topics: 'आंशिक रूप से देखा गया विषय',
    notAtAll_Viewed_Topics: 'बिल्कुल नहीं देखा विषय पर',
    user_viewed_topics:'उपयोगकर्ता ने देखा विषय',
    topic_users: 'छात्र',
    clear_room_chat: 'चैट हटाएं',
    delete_room_chat_alert: 'क्या आप वाकई चैट को साफ़ करना चाहते हैं?',
    join: 'में शामिल होने के',
    access_denied : 'पहुंच अस्वीकृत',
    video_bit_rate: 'वीडियो बिट दर',
    audio_bit_rate: 'गानों का बिट दर',
    evaluate_assignment:'असाइनमेंट का मूल्यांकन करें',
    back_to_submissions: 'वापस प्रस्तुतियाँ',
    Persian: 'Persian',
    submit :'जमा करें',
    make_speaker_vedio : 'स्पीकर बनाएं',
    Connection_Request : 'कनेक्शन अनुरोध',
    message:'संदेश',
    sources:'सूत्रों का कहना है',
    resolutions:'संकल्प',
    camera :'कैमरा',
    Audio_Inputs:'ऑडियो इनपुट',
    Please_enter_Company: 'कृपया कंपनी दर्ज करें',
    Please_enter_Position: 'कृपया स्थिति दर्ज करें',
    Please_enter_valid_City_Town: "'कृपया मान्य शहर / नगर दर्ज करें' (विशेष अनुयायियों को अनुमति नहीं दी जानी चाहिए)",
    Please_enter_valid_Country: 'कृपया मान्य देश दर्ज करें',
    Please_enter_valid_From_Date: 'कृपया वैध दिनांक दर्ज करें',
    From_date_cannot_be_in_future: 'तिथि से भविष्य में नहीं हो सकता',
    Please_enter_valid_To_Date: "कृपया वैध तिथि दर्ज करें",
    From_date_and_To_date_cannot_be_same: 'तिथि और तिथि से समान नहीं हो सकता',
    To_date_should_be_greater_than_From_date: 'तिथि करने के लिए तिथि से अधिक होना चाहिए',
    Please_enter_School: 'कृपया स्कूल दर्ज करें',
    School_field_cannot_have_empty_spaces: "स्कूल के मैदान में रिक्त स्थान नहीं हो सकते",
    Please_enter_University: 'कृपया विश्वविद्यालय दर्ज करें',
    University_field_cannot_have_empty_spaces: "विश्वविद्यालय के क्षेत्र में रिक्त स्थान नहीं हो सकते",
    Please_enter_atleast_one_skill: "कृपया कम से कम एक कौशल दर्ज करें",
    Please_enter_Address: 'कृपया पता दर्ज करें',
    Please_enter_a_valid_Address: 'कपया वैध पता अंकित करें',
    Please_enter_City: 'कृपया शहर दर्ज करें',
    Please_enter_a_valid_City: 'कृपया एक मान्य शहर दर्ज करें',
    Please_enter_Zip: "कृपया ज़िप दर्ज करें",
    Please_enter_a_valid_Zip: 'कृपया एक वैध ज़िप दर्ज करें',
    Please_enter_website: 'कृपया एक वैध ज़िप दर्ज करें',
    Please_enter_valid_website: 'कृपया वैध वेबसाइट दर्ज करें',
    Please_enter_social_link: 'कृपया सामाजिक लिंक दर्ज करें',
    Please_enter_valid_social_link: 'कृपया मान्य सामाजिक लिंक दर्ज करें',
    Please_enter_valid_Date_of_birth: 'कृपया जन्म तिथि की वैध तिथि दर्ज करें',
    Date_of_birth_cannot_be_future_Date: "जन्म तिथि भविष्य की तिथि नहीं हो सकती",
    Please_select_Gender: ' कृपया लिंग चुनें',
    Please_enter_Current_Password: 'कृपया वर्तमान पासवर्ड दर्ज करें',
    Please_enter_New_Password: 'कृपया नया पासवर्ड दर्ज करें',
    Please_enter_Confirm_password: 'कृपया पासवर्ड की पुष्टि करें दर्ज करें',
    New_Password_and_Confirm_password_should_be_same: 'नया पासवर्ड और पासवर्ड की पुष्टि करना समान होना चाहिए।',
    Assignment_name_cannot_have_only_white_spaces: "असाइनमेंट नाम में केवल सफेद स्थान नहीं हो सकते",
    Please_enter_Assignment_Name: 'कृपया असाइनमेंट नाम दर्ज करें',
    Please_enter_Question: 'कृपया प्रश्न दर्ज करें',
    please_select_type: ' कृपया प्रकार चुनें',
    Please_enter_Options: ' कृपया विकल्प दर्ज करें',
    Provide_atleast_Two_Options: 'कम से कम दो विकल्प प्रदान करें',
    Options_cannot_be_same: "विकल्प समान नहीं हो सकते",
    Please_select_an_Answer: 'कृपया एक उत्तर चुनें',
    Marks_cannot_be_empty: "मार्क्स रिक्त नहीं हो सकते",
    Marks_can_only_have_Numbers: ' अंक में केवल नंबर हो सकते हैं',
    Please_enter_a_valid_Name: ' कृपया कोई मान्य नाम दर्ज करें',
    Please_enter_valid_Email_id: 'कृपया मान्य ईमेल आईडी दर्ज करें',
    Please_enter_Password: ' कृप्या पास्वर्ड भरो',
    Passwords_are_not_matching: 'पासवर्ड मेल नहीं खाते हैं',
    Please_enter_valid_City_Name: 'कृपया मान्य शहर का नाम दर्ज करें',
    Please_enter_valid_State_Name: ' कृपया वैध राज्य नाम दर्ज करें',
    Please_accept_Term_conditions: 'कृपया नियम एवं शर्तें स्वीकार करें',
    Please_enter_institute_name: 'कृपया संस्थान नाम दर्ज करें',
    Enter_at_least_three_letters_to_search: 'खोज करने के लिए कम से कम तीन अक्षर दर्ज करें',
    profile_picture:'प्रोफ़ाइल फोटो',
    search_members_add : 'अपने गोरुप में जोड़ने के लिए संपर्क खोजें.',
    delete_group : 'समूह हटाएं',
    addlocation : 'स्थान बताईए',
    access_denied : 'पहुंच अस्वीकृत',
    edit_category: 'श्रेणी संपादित करें',
    select_company : 'कंपनी का चयन करें',
    select_gender : 'लिंग चुनें',
    old_pwd : 'पुराना पासवर्ड',
    new_pwd : 'नया पासवर्ड',
    re_new_pwd : 'नया पासवर्ड दोबारा टाइप करें',
    result_details : 'परिणाम विवरण',
    create_group : 'समूह बनाएँ',
    Please_select_any_option :'कृपया कोई भी विकल्प चुनें',
    phne:'फ़ोन',
    go_back:'वापस जाओ',
    Current:'वर्तमान',
    Personal_Information : 'व्यक्तिगत जानकारी',
    Work_Places : 'कार्य स्थल',
    dob:'जन्म तिथि',
    Social_Links:'सामाजिक लिंक',
    Connections : 'कनेक्शन',
    All_Connections:'सभी कनेक्शन',
    View_all: 'सभी को देखें',
    Hide_all:'सभी छुपाएं',
    hide: 'छिपाना',
    enter_schedule_password: 'शेड्यूल पासवर्ड दर्ज करें',
    conference_access: 'सम्मेलन का उपयोग',
    please_enter_schedule_password: 'कृपया शेड्यूल पासवर्ड दर्ज करें',
    support_center: 'समर्थन केंद्र',
    open_a_new_ticket: 'एक नई टिकट खोलें',
    check_ticket_status: 'टिकट स्थिति की जांच करें',
    troubleshoot: 'समस्या निवारण करें',
    invalid_or_expire_room: 'यह एक अमान्य पाठ्यक्रम दिखता है या आपका कोर्स समाप्त हो गया है',
    unautharized_request: 'यह एक असामान्य अनुरोध दिखता है',
    invalid_user: 'ऐसा लगता है कि आप एक अमान्य उपयोगकर्ता हैं',
    invalid_room: 'यह एक अमान्य पाठ्यक्रम दिखता है',
    invalid_or_expire_package: 'यह एक अमान्य पैकेज दिखता है या आपका पैकेज समाप्त हो गया है',
    export_chat: 'निर्यात चैट',
    download_certificate: 'प्रमाणपत्र डाउनलोड करें',
    topics_completed: 'पूर्ण किये गए विषय',
    certificates: 'प्रमाणपत्र',    
    certificate_approved: 'प्रमाणपत्र स्वीकृत करें',
    select_questionnaire : "प्रश्नावली का चयन करें",
    questionnaire_name_error : "कृपया प्रश्ननाम नाम दर्ज करें",
    questionnaire_description_error : "कृपया विवरण दर्ज करें", 
    clone_from_previoues_questionnaire: "पिछले प्रश्नावली से क्लोन",
    select_questionnaire: "कृपया प्रश्नावली चुनें",
    topic_completed: 'यदि विषय पूर्ण हो जाता है',
    i_have_completed_this_topic: 'कंने विषय पूरा कर लिया है',
    continous_user_presence_exceeded : 'उपयोगकर्ता की सीमा पार हो गई, कृपया व्यवस्थापक से संपर्क करें',
    update_basic_information : 'बुनियादी जानकारी अपडेट करें',
    adding_question_please_wait : 'सवाल जोड़ना, कृपया प्रतीक्षा करें...',
  },
};
