export const SET_STARTUP_PENDING = 'SET_STARTUP_PENDING';
export const SET_USER_DETAILS = 'SET_USER_DETAILS';
export const SET_USER_AUTH_TOKEN = 'SET_USER_AUTH_TOKEN';
export const SET_MOBILE_NUMBER_VERIFICATION = "SET_MOBILE_NUMBER_VERIFICATION";
export const SET_CONSENT_PAGE_VERIFICATION = "SET_CONSENT_PAGE_VERIFICATION";
export const SET_MEDICAL_FORM_FILLING = "SET_MEDICAL_FORM_FILLING";
export const SET_STARTUP_ERROR = 'SET_STARTUP_ERROR';