export const SET_DOCTOR_PROFILE_PENDING = 'SET_DOCTOR_PROFILE_PENDING';
export const SET_DOCTOR_PROFILE_SUCCESS = 'SET_DOCTOR_PROFILE_SUCCESS';
export const SET_DOCTOR_PROFILE_ERROR = 'SET_DOCTOR_PROFILE_ERROR';
export const SET_CHANGE_PASSWORD_PENDING = "SET_CHANGE_PASSWORD_PENDING"
export const SET_CHANGE_PASSWORD_SUCCESS = "SET_CHANGE_PASSWORD_SUCCESS"
export const SET_CHANGE_PASSWORD_ERROR = "SET_CHANGE_PASSWORD_ERROR"