-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg8+melvVvECN0Huj6nHLI+MKXMAS9cpUMPCNpjs/pK4ygCgYIKoZIzj0DAQehRANCAAR30Hg8hNK4yVMULfJGSQCAhHjnyVW4aCYulD3/QfeEowSnwh8T35ZXpUShhwA3YpflXP1JT0R6kYRO9d/ui8PF
-----END PRIVATE KEY-----