export const SET_PATIENT_REGISTRATION_PENDING = 'SET_PATIENT_REGISTRATION_PENDING';
export const SET_PATIENT_REGISTRATION_SUCCESS = 'SET_PATIENT_REGISTRATION_SUCCESS';
export const SET_PATIENT_REGISTRATION_ERROR = 'SET_PATIENT_REGISTRATION_ERROR';